### ISSUE TITLE
很奇怪的编译错误

### ISSUE THREAD

**Issue by songpo** [alibaba/HandyJSON#101]
Xcode版本：Version 8.2.1 (8C1002)
Swift版本：3.0
错误信息： Command failed due to signal: Segmentation fault: 11

```
import Foundation
import HandyJSON

struct Meeting: HandyJSON {

    /** 主键 */
    var id = ""
    /** 名称 */
    var name = ""
    /** 安全码 */
    var secret = ""
    var creator: User?
   // ==================编译正常================
    var noerror: [User]?
    /** 创建时间 */
    var createTime = ""
    /** 流列表 */
    var streams: [StreamInfo]?
    // =================编译错误=================
    var error: StreamInfo?

}
```

```
import Foundation
import HandyJSON

struct User: HandyJSON  {
    
    /** 主键 */
    var id = ""
    /** 账号 */
    var username = ""
    /** 昵称 */
    var nickname = ""
    /** 邮箱 */
    var email = ""
    /** 手机 */
    var mobilePhone = ""
    /** 身份证号 */
    var idcard = ""
    /** 创建时间 */
    var createTime = ""
    
}
```

```
import Foundation
import HandyJSON

struct StreamInfo: HandyJSON  {

    /** 主键 */
    var id = ""
    /** app */
    var app = ""
    /** tcURL */
    var tcUrl = ""
    /** 流主键 */
    var streamId = ""
    /** 客户端主键 */
    var clientId = ""
    /** IP地址 */
    var ip = ""
    /** vHost */
    var vHost = ""
    /** pageUrl */
    var pageUrl = ""
    /** 创建人 */
    var creator: User!
    /** 创建时间 */
    var createTime = ""
    /** 所属会议 */
    var meeting: Meeting!
}
```

**Comment by xuyecan** [comment]
注释的 `编译正常`/`编译错误` 具体是什么意思呢？

**Comment by songpo** [comment]
// ==================编译正常================
    var noerror: [User]?
是指的加入这个数组的属性，能够正常编译

 // =================编译错误=================
    var error: StreamInfo?
是指的加入这个数组的属性，编译就会报错
 Command failed due to signal: Segmentation fault: 11

**Comment by xuyecan** [comment]
我这边编译了一下，错误很明显的：

```
SampleModel.swift:13:8: Value type 'Meeting' cannot have a stored property that references itself
```

`Meeting` 和 `StreamInfo` 都是值类型，它们不能在定义里存在“循环包含“关系，因为会导致它们的size互相依赖，没办法决定出来。改成class就没问题了。

**Comment by songpo** [comment]
非常感谢您的回答！对Swift的class和struct不是很了解具体的实现机制，看网上介绍说struct如何如何好用，还是没了解清楚！再次感谢！

**Comment by xuyecan** [comment]
不客气 :)

**Comment by banxi1988** [comment]
@songpo  WWDC 有好几个 Session 是关于  Struct 的 也有关于它跟 Class 的性能比较.
简单来说 Class 属于引用属性,  Struct 是值类型. 具体一点, Class 变量只是一个指针,指向类在堆中分配的对象. 而 struct 类型变量指向的是其在栈的包含所有结构变量的内存结构

之前没遇到过这个问题, 发现还是挺有意思的问题. 下面谈谈我的看法.

如下: 一个账号可能有一张卡,一张卡必定有所属的账号. 这在业务逻辑上是通的.
但是

```swift
struct Card{
  let cardNo:String
  let owenr:Account
}

struct Account{
  let name:String
  var card:Card?
}
```
但是在栈的内存表示上却造成了问题. struct 的语义是整个结构都放在栈内存上的.
所以, Card 结构所占用的栈内存是  cardNo 占内存大小 +  owner(Account) 占用的内存大小.
而 Account 所占用的内存大于,又是 name 的内存占用大小 + card(Card) 内存占用的大小.
生成了鸡生蛋,蛋生鸡的问题.

所以解决办法是将其中一个 改为 `class` 类型就可以了.
如:

```swift
struct Card{
  let cardNo:String
  let owenr:Account
}

class Account{
  let name:String = ""
  var card:Card?
}
```

这个时候 Card 结构所占用的内存大小就是可计算的了,
因为这个时候 owner 变量只是一个指针, 其大小是确定的.

**Comment by songpo** [comment]
var creator: User?
   // ==================编译正常================
    var noerror: [User]?
    /** 创建时间 */
    var createTime = ""
    /** 流列表 */
    var streams: [StreamInfo]?
    // =================编译错误=================
    var error: StreamInfo?
实际上问题描述的还不是太清晰，出现的问题如下：
1、当存在User属性时，再加一个User的数组，编译是正常的
2、现在已经存在了一个StreamInfo的数组，当再加入一个StreamInfo类型的stream属性时，编译器就报错

StreamInfo中，有一个User类型的creator属性，有可能是在这个时候，StreamInfo包含了对User的引用。
原来我是想在meeting中增加一个创建人，一个创建人的流信息，但是，编译报错了，我这儿编译的时候，仅仅报出了，我之前贴的那个错误，并没有很明确的报错信息。

现在我还是决定简化对象的引用关系，只保留一对一之间的关系，移除了一对多的关系，在不能使用双向关系的时候，单向的关系也是个不错的选择
