### ISSUE TITLE
将model类型转化为JSON的时候 出现了问题

### ISSUE THREAD

**Issue by guotengda** [alibaba/HandyJSON#102]
class testModel: HandyJSON {
    var id: NSNumber?
    var name: String?
    var age: Int?
    var array:[String]?
    required init() {}
}
func testDic() {
        let dic:NSDictionary = ["id":"0",
                   "name":"1",
                   "age":"2",
                   "array":["1", "2", "3"]]
        let object = testModel.deserialize(from: dic)
        print("\(object?.toJSON()!)")
        print("\(object?.toJSONString()!)")
        print("\(object?.toJSONString(prettyPrint: true)!)")
}

我发现如果key是 id:NSNumber  调用model.toJSON方式的时候 会出现crash
fatal error: Should not call this on HandyJSON model: file /Users/xiucheren/Downloads/HandyJSON-master/HandyJSON/Protocol.swift, line 160

我修改id的类型为String？
往下进行
然后发现似乎是在数据转化为model之前的类型要和model的key的类型要匹配？   否则不能逆向转化？

**Comment by xuyecan** [comment]
1.6.1版本应该已经修复了这个关于`NSNumber`类型的问题，你测试下？

**Comment by xuyecan** [comment]
有问题请再提出~
