### ISSUE TITLE
多个json key映射同一个属性应该怎么做？

### ISSUE THREAD

**Issue by hejunbinlan** [alibaba/HandyJSON#103]
类似oc三方库YYModel中的：
+ (NSDictionary *)modelCustomPropertyMapper {
    return @{@"name" : @"n",
             @"page" : @"p",
             @"desc" : @"ext.desc",
             @"bookID" : @[@"id",@"ID",@"book_id"]};
}

**Comment by xuyecan** [comment]
目前还不支持多个自定义Key映射到同一个字段，我将会在下个版本支持。

**Comment by xuyecan** [comment]
@hejunbinlan 引入 1.7.1 版本，在定义mapper方法时，可以：
```swift
func mapping(mapper: HelpingMapper) {
    mapper <<<
        self.id <-- ["id1", "id2", "id3"]
}
```
这样去为一个字段映射多个key。
