### ISSUE TITLE
提一个1.6.1版本上的bug

### ISSUE THREAD

**Issue by ac1217** [alibaba/HandyJSON#106]
model:
struct addClient: JSONModel {
        
        var sessionId = ""
        var area = ""
        var avatar = ""
        var city = ""
        var contact = ""
        var contactPhone = ""
        var name = ""
        var phone = ""
        var province = ""
        var comTypeId = ""
        
        var remark: String?
        var email: String?
        var address: String?
}
有3个optionl类型字符串参数

在1.6.0版本是反序列化是没问题的：
["city": "340700", "name": "gmgm ", "comTypeId": "dde43f0922994ef1b7782dcced84e9be", "email": "ddd@ss.com", "address": "gmgm", "sessionId": "45d15a3675e74e048dc9a55099daa918", "province": "340000", "contactPhone": "13945784515", "avatar": "/upload/avatar/cbc79de2-f049-4157-bace-867985974534.png", "contact": "gmgm", "phone": "13854275481", "remark": "fmfmnf", "area": "340702"]

在1.6.1版本
["city": "340700", "name": "gmgm ", "comTypeId": "dde43f0922994ef1b7782dcced84e9be", "email": Optional("ddd@ss.com"), "address": Optional("gmgm"), "sessionId": "45d15a3675e74e048dc9a55099daa918", "province": "340000", "contactPhone": "13945784515", "avatar": "/upload/avatar/cbc79de2-f049-4157-bace-867985974534.png", "contact": "gmgm", "phone": "13854275481", "remark": Optional("fmfmnf"), "area": "340702"]

反序列后optional参数不为nil时变成这样了
"email": Optional("ddd@ss.com")
"address": Optional("gmgm")
"remark": Optional("fmfmnf")
字符串直接变成 Optional(xxx）

但是我希望是跟1.6.0版本的一样，所以请教下

**Comment by ac1217** [comment]
大神在1.6.1版本测试下是否正确

**Comment by xuyecan** [comment]
你好，你这里是把Model序列化为字典后遇到的问题吧？因为我看到你这里的两个结果，像是直接打印一个字典得到的。

如果是把Model序列化为字典的话，每个值都会保持它原本的类型，那么可选值就是应该在控制台打印出Optional("xxxx")形式。我测试1.6.0和1.6.1行为是一致的。

或者，你把你的Model精简一下，然后完整代码贴一下吧？

**Comment by ac1217** [comment]
我试过1.6.0和1.6.1,上传到服务器，然后从服务器请求回来的数据不一样，1.6.0不会出现optional("xxx"),而1.6.1会的，像这样，应该是转字符串的时候出现问题
<img width="373" alt="bcddafb6-cf85-4c39-a321-2c7cc5242473" src="https://cloud.githubusercontent.com/assets/12161956/24285064/590217d6-10a9-11e7-918d-a348399e88bc.png">
从服务器返回的数据是这样子，说明当时传上去是个【Optional("yuggffg")】这样的字符串

**Comment by xuyecan** [comment]
能否把上传的内容打印一下呢？顺便贴一下这段逻辑的代码。

**Comment by xuyecan** [comment]
1.6.0和1.6.1版本的代码差异只有这个提交：https://github.com/alibaba/HandyJSON/commit/2e96b9f27ba1adbc775313ee36b6168789cb3538 ，理论上不会引起本issue中的序列化问题。
