### ISSUE TITLE
HandyJson + Realm 冲突

### ISSUE THREAD

**Issue by geGao123** [alibaba/HandyJSON#107]
Model同时继承Realm的Object类，实现HandyJson的HandyJSON协议，会使HandyJson赋值错误

**Comment by xuyecan** [comment]
请贴一下最简示例代码我测试一下。

**Comment by jim-binea** [comment]
我也遇到问题，使用了HandyJson解析出来的对象无法使用realm保存，realm会报错，大概是：reamlObject已经被其他realm manager管理了。具体不记得了。猜测可能是修改了realm对象的某些属性导致的。。。现在纠结要不要换其他库了。希望尽快修复

**Comment by xuyecan** [comment]
已经验证问题存在。

排查发现，继承自Realm `RLMObjectBase`的类在构造实例时，会调用`object_setClass`将自己的metaclass替换为动态生成的proxy类型。该proxy类型是在objc-runtime中使用`objc_allocateClassPair`构造的，swift相关内存域只是简单置空，导致swift-runtime中尝试读取该区域信息时指针访问非法。

目前我想到的解决方案是：遇到这种情况，忽略该metaclass的swift相关信息(这个目前来看不会产生副作用)，而直接处理superclass(利用`objc_allocateClassPair`创建的类继承自原始类)。

同时我强化了一下限制，`HandyJSON`将忽略所有在objc-runtime中的属性，因为objc-runtime中对象布局信息、规则和swift是不一样的，目前先不做兼容支持。

参考： https://github.com/alibaba/HandyJSON/pull/110/commits

**Comment by xuyecan** [comment]
整理后将发布1.6.2版本。

**Comment by xuyecan** [comment]
@geGao123 @jim-binea 已经修复此问题并发布1.7.1版本，请更新重试。

**Comment by whisper-bye** [comment]
@xuyecan 
刚好有这个需求，HandyJSON现在能和Realm配合使用了吗？
