### ISSUE TITLE
编译错误

### ISSUE THREAD

**Issue by yusoul** [alibaba/HandyJSON#108]
Showing Recent Issues
Command /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swiftc failed with exit code 1

最新的xcode 8.3编译报错

**Comment by jackrex** [comment]
这个怎么解决的
same issus

**Comment by kLike** [comment]
也遇到了，怎么解决啊，弄半天了

**Comment by CoderLT** [comment]
same issus

**Comment by xuyecan** [comment]
@jackrex @CoderLT 是否能提供最简复现工程，我这边测试一下。注意要引入最新版本，1.7.0。

**Comment by CoderLT** [comment]
最新版本已经解决
