### ISSUE TITLE
提一个建议，望改进

### ISSUE THREAD

**Issue by Mosaics** [alibaba/HandyJSON#109]
大家都知道，现在网络请求的数据多数以json格式解析，json格式有个好处是在控制台打印出来后有结构性，结构层次一清二楚，虽然也可以将请求的json格式转换成json字符串，但是通过字符串转换相当的不直观，不知道能不能以json格式转换？我吃了几次亏，后台接口写的字段和实际的并不相符，我建模型的时候字段老是对不上，还在傻傻的去找错误！实际上json字符串一长串，根本就不好找。

归根结底，现在只支持jsonString -> model, 并不支持json -> model
其实我觉得提供额外方法（最偷懒的做法）也快，直接将返回的json序列化成字符串再调用现有的接口即可

**Comment by xuyecan** [comment]
你意思是，当拿到网络层返回的数据的时候，已经是JSON格式了，并不是字符串，对吧？那请问下，这个JSON格式，具体是代码中的什么类型呢？

如Foundation中提供的`JSONSerialization.jsonObject(with:options:)`函数，实际上，它的返回值实际是`NSArray`或者`NSDictionary`，是可以转换成`NSArray`/`NSDictionary`然后通过`HandyJSON`现有的API进行反序列化的。

**Comment by Mosaics** [comment]
这个我是知道的，我的建议里也是这么说的，只是不足的一点，返回一个字符串直观看起来，json的层次结构并不是那么好看，建模的时候困难，必须要自己反序列化成标准的json格式树，才知道怎么建模。所以我才想能不能你这边的库层级提供一个api通过json格式序列化。其实内部也就是你说的 将传入的json再序列化成字符串就能满足你当前的接口调用。仅仅只是对外方便些

**Comment by xuyecan** [comment]
@Mosaics 我还是不是特别理解。“所以我才想能不能你这边的库层级提供一个api通过json格式序列化”这句话里指的‘JSON格式’具体是什么格式？在代码里，它的类型是什么呢？

**Comment by Mosaics** [comment]
比如 swift里 Alamofire 请求返回的 responseJSON方法的json格式

**Comment by Mosaics** [comment]
其实这也不是一个必选项，建模可以按接口文档来写。但如果需要有容错检查，我还是觉得还是有必要提供这么一个api（虽然不提供也就是代码里面多几句转换）

**Comment by Mosaics** [comment]
这么说吧，其实就是实现你这个功能。

**Comment by xuyecan** [comment]
@Mosaics 我明白你意思了。但是，正如‘Alamofire 请求返回的 responseJSON方法的json格式’，它的`responseJSON()`中拿到的数据，实际正是从`JSONSerialization.jsonObject(with:options:)`得到的(Alamofire文档明确提到它使用NSJSONSerialization做JSON反序列化)。它是`Any`类型，实际使用时，需要转换到`NSDictionary`或者`Dictionary<String, Any>`，而`HandyJSON`是有接口直接接受这两个类型的。

所以这就是我要说的，其实没必要先转换到String，直接做个cast就可以传入`HandyJSON`现有的接口了。

**Comment by Mosaics** [comment]
是的，我也这么觉得。搞成string,就算解析数据建模照着接口文档写，万一有容错，字符串找都找不到，一点都不直观。

**Comment by xuyecan** [comment]
所以现在不需要修改了呀。Foundation提供的NSJSON相关的方法，在提到`JSON格式`时，指的东西本质上一般是`NSDictionary`(虽然JSON顶层对象也允许`NSArray`)。现在的接口是支持的。

```
public static func deserialize(from dict: NSDictionary?, designatedPath: String? = nil) -> Self?
```

**Comment by Mosaics** [comment]
….感觉饶了一圈，我知道这些方法，我想说的是，其实就是实现 
Features

里的 From JSON 接口，虽然现在做到这个程度已经可以了 自己本身就可以支持

**Comment by xuyecan** [comment]
@Mosaics 但你想一下，如果要提供一个`FromJSON`接口，接口形式是怎样的呢？

是 `deserialize(from json: NSDictionary?)`，
还是 `deserialize(from json: Any?)`呢？

**Comment by xuyecan** [comment]
如上述，暂不考虑添加此接口。
