### ISSUE TITLE
Nested Objects Lost In 1.6.1 Version

### ISSUE THREAD

**Issue by jarkoAndroid** [alibaba/HandyJSON#111]
we have a json of object 
{
"field1" : "something",
"field2" : 2,
"nestedObject" : {"nestedProperty" : 1, "nestedProperty2" : "something" }
}
and a corresponding classes in Swift:

class Nested: HandyJSON{
var nestedProperty: ... ? = nil
var nestedProperty2: ... ? = nil
required init(){}
}

class Something : HandyJSON {
var field1: String? = nil
var field2: Int? = nil
var nestedObject: Nested? = nil
required init(){}
}
and after call of func toJSONString there are no nested objects in result
we are sad(((
WE ARE SAD((((

**Comment by ssuhanov** [comment]
It will be fixed with this pull-request: https://github.com/alibaba/HandyJSON/pull/112

**Comment by xuyecan** [comment]
I tested the following code and found no problem:

```swift
class Nested: HandyJSON {
    var nestedProperty: String? = nil
    var nestedProperty2: String? = nil
    required init(){}
}

class Something : HandyJSON {
    var field1: String? = nil
    var field2: Int? = nil
    var nestedObject: Nested? = nil
    required init(){}
}

func tested() {

    let something = Something()
    something.field1 = "field1 string"
    something.field2 = 1
    let nest = Nested()
    nest.nestedProperty = "nested 1"
    nest.nestedProperty2 = "nested 2"
    something.nestedObject = nest

    if let jsonString = something.toJSONString() {
        print("serialize: ", jsonString)
        if let another = Something.deserialize(from: jsonString) {
            print("deserialize: ", another.nestedObject?.nestedProperty ?? "")
        }
    }
}

tested()
```

It printed:

```
serialize:  {"field1":"field1 string","nestedObject":{"nestedProperty":"nested 1","nestedProperty2":"nested 2"},"field2":1}
deserialize:  nested 1
```

If i didn't catch the right point, please offer me more details. i will look into it immediately.

**Comment by ssuhanov** [comment]
I see this in the console now. My object is `Optional Dictionary`, but it has nested NSDictionaries. And when I call `toJSONString()` I lose nested objects. :(
```
(lldb) po myJSON
▿ Optional<Dictionary<String, AnyObject>>
  ▿ some : 5 elements
    ▿ 0 : 2 elements
      - key : "dateMatch"
      - value : 1484252100
    ▿ 1 : 2 elements
      - key : "id"
      - value : 1275768
    ▿ 2 : 2 elements
      - key : "result"
      - value : 3 - 3
    ▿ 3 : 2 elements
      - key : "homeTeam"
      ▿ value : 3 elements
        ▿ 0 : 2 elements
          - key : id
          - value : 26734
        ▿ 1 : 2 elements
          - key : image
          - value : /images/logos/26734.png
        ▿ 2 : 2 elements
          - key : name
          - value : Севилья
    ▿ 4 : 2 elements
      - key : "awayTeam"
      ▿ value : 3 elements
        ▿ 0 : 2 elements
          - key : id
          - value : 26673
        ▿ 1 : 2 elements
          - key : image
          - value : /images/logos/26673.png
        ▿ 2 : 2 elements
          - key : name
          - value : Реал Мадрид


(lldb) po myJSON?.toJSONString()
▿ Optional<String>
  - some : "{\"id\":\"1275768\",\"result\":\"3 - 3\",\"dateMatch\":\"1484252100\"}"
```

Here's screen:
<img src="https://ssuhanov.files.wordpress.com/2017/04/screen-shot-2017-04-05-at-12-34-43.png">

**Comment by xuyecan** [comment]
Yes, now i know what the problem was. In @ssuhanov's case, there was a `NSDictionary` type property in the model. But `NSDictionary` wasn't conform to any `Transformable` protocol which made it lost in the serialization/deserialization now. I will fix this soon.

But still, i think this is not related to the issue @jarkoAndroid came across.

**Comment by xuyecan** [comment]
Import `pod HandyJSON, '1.7.1'` and retry :)
Reopen this if issue persist.
