### ISSUE TITLE
Xcode更新到8.3之后报错

### ISSUE THREAD

**Issue by guoguoli** [alibaba/HandyJSON#114]
更新到Xcode8.3之后报错 Command /Applications/Xcode8.3.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swiftc failed with exit code 1

**Comment by xuyecan** [comment]
你用的是最新代码吗？我现在一直用的xcode8.3开发，貌似没什么问题。

**Comment by xuyecan** [comment]
请引入1.6.1以上的版本，应该没问题的。

**Comment by guoguoli** [comment]
使用最新版本还是有以上问题。只能用Xcode8.2打包运行项目

**Comment by xuyecan** [comment]
前端时间比较忙，不好意思。现在还有问题吗？可以加群讨论：581331250。
