### ISSUE TITLE
如何处理jsonArray？

### ISSUE THREAD

**Issue by gongyucheng** [alibaba/HandyJSON#115]

**Comment by xuyecan** [comment]
能具体说一下吗？原始数据是什么样子，需要转换为什么形式？

**Comment by gongyucheng** [comment]
@xuyecan 返回的是一个数组类型的json，转成model元素的数组，但是我看方法里只有dictionary和string两种参数

**Comment by xuyecan** [comment]
目前没有封装这样的方法。但只需要调用一下 `[json].map( json -> Model )` 就可以了，应该也挺方便的吧。

**Comment by gongyucheng** [comment]
@xudafeng 因为网络请求返回的结果已经是NSArray或者NSDictionary了，如何处理啊？

**Comment by xuyecan** [comment]
@gongyucheng 
1. HandyJSON有提供 `public static func deserializeFrom(dict: NSDictionary?, designatedPath: String? = nil) -> T?` 形式的api；
2. 如果是NSArray，需要自己遍历Array，对每一个元素进行解析；

**Comment by gongyucheng** [comment]
@xudafeng 了解了，还有一个问题，json->model后部分属性为nil，使用的时候需要没一个都要 if (id != nil)进行判断吗？现在不支持容错机制是吗？

**Comment by xuyecan** [comment]
需不需要判断要看你的model中，各个属性的定义是否为可选类型，和JSON转换没关系。只是说，如果转换时，JSON中没找到对应字段的值，或者类型不匹配，就不进行赋值。
