### ISSUE TITLE
关于实现原理和Swift版本兼容性问题

### ISSUE THREAD

**Issue by youngsoft** [alibaba/HandyJSON#116]
你的原理是基于现有swift版本对象的内部数据结构来实现的，但是内部数据结构并不是公开的文档而且可能随时变化(OC1.0和OC2.0的runtime内存结构就不相同)。**一旦操作系统升级那么所有使用这个库应用都将是灾难的！** 这个东西只适合用来学习而不适合用于真实系统应用。因为从你的项目的升级适配改动的内存结构到上线之间是有时间差的。

**Comment by xuyecan** [comment]
1. 是的，原理是基于Swift运行时对象的内存布局来实现的，但是，Swift对象的内存布局在一个库被编译时，就已经决定了，且不可更改。也就是说，只和编译时的Swift版本有关，和操作系统版本无关。
2. Swift和Objective-C不同，至少在目前，它是一门偏向于“类C++“的静态语言，例如，编译后，方法的调用非运行时派发，而是基于偏移量寻址。这意味着什么呢？这意味着，一旦某个库被编译出来，它依赖的其他库就不能有内存布局的变更，否则直接将导致二进制不兼容！参考：[Swift库二进制接口(ABI)兼容性研究](http://www.jianshu.com/p/5860f5542f21)。

总结下来，就是，将HandyJSON应用到生产环境，不会因为操作系统升级就发生不兼容的情况，苹果自己必须保证这一点，不然所有的有动态库依赖的Swift程序都面临问题。

本项目对Swift对象内存布局的解析，依据来自Swift官方ABI文档：https://github.com/apple/swift/blob/master/docs/ABI.rst 。确实，Swift目前没有官方声明确保未来ABI稳定(至少Swift 1， Swift 2， Swift 3 演进过程都保证了稳定，而且Swift的ABI还需要考虑兼容Objective-C的内存布局)，但，如果Swift发布了破坏ABI兼容性的新版本，那所有已发布的Swift二进制程序、动态库都需要重新编译。那么，这时候是有时间发现不兼容问题并解决问题的。

退一步说，即使Swift发布了ABI不兼容的版本，本项目又没有第一时间更新，那只要用旧版本编译，一切就不会有问题。

**Comment by youngsoft** [comment]
我跟踪了一下你的代码实现和大概想了一下和翻了一下相关的资料。对于结构体的定义我想SWIFT应该和C/C++是一样的也就是编译时的代码中属性的访问其实就是内存指针偏移量的访问，而class则有一些差异。从文档上说每个Swift对象的头8个字节(64)应该是保存这这个类的类元信息，这个也和OC的对象结构相似。你这个实现原理是从swift的类元定义中读取所有定义的属性出来然后将字典中的同名key的内容，再赋值到结构体的内存偏移地址中去，我比较好奇的是如果是这样的话如果是对象的话可能还会存在一个引用计数的问题如何去解决的？ 比如OC中属性又weak,strong,copy的情况，那这种属性赋值其实内部是调用了不同的方法来完成的，如果按照我的理解你只是将字典中的value部分写入swift结构体中的内存偏移中去，那是否会存在一些问题，也就是你是否可以确保对于swift结构体的属性赋值，在编译为二进制时就只是简单的内存地址偏移上的静态赋值？不会做其他的事情。。。
 还有一点的是swift的类元信息也是一段静态的数据结构，也就是在编译时也基本确定了内存结构和位置，并且每个swift结构体实例的头8个字节都指向这个内存。我的问题是否swift的runtime库在读取这些类元信息时是否也真是按你代码里面的直接取每个实例的头8个字节来获取类元信息，还是可能这种加载机制会变化。。。。因为我也有研究过OC2.0的内存结构，我开始以为OC的引用计数是保存在对象中的，后来通过看汇编代码发现这个引用计数变量并非保存在对象的内存布局中，而好像是保存在了一个动态的第三方的HASH散列表里面（我记得以前windows的COM技术里面的引用计数是保存在对象自身的内存布局中的）

**Comment by youngsoft** [comment]
再补充一句的是如果都是静态连编的话那这个解决方案确实是一个优秀的解决方案。！！ 

但我还是对于JSON和MODEL之间的转化各种框架持保留态度的。原因是客户端有客户端的业务和对象数据模型，服务端有服务端的对象数据模型。而网络传输时有传输时的数据模型。这三个模型结构应该是独立而不是依赖的，这样有利于降低耦合度。因此我不建议客户端的数据模型是由JSON的格式来决定的。而应该是一个独立于JSON格式的数据模型。举例来说假设服务器返回一个层次结构的银行树。对于JSON可能如下格式：

```
  { “name":"bank1", "id":"1", "subbank":[
    {
        "name":"subbank1", "id":"12"
    }, ...
]
  }

```

但实际中我们应该这样设计银行模型更加合理：

```
struct Bank
{
    var name:String
    var id:Int
    var subbank:[Bank]
    weak var parentBank: Bank
}

```
如果客户端模型是依赖于网络传输的JSON结构而定义的话，那么一旦JSON结构的命名改变，那么客户端的模型也要跟着改变，如果我们的模型可能提供给第三方使用的话，那么意味着使用者也要跟着改变。而如果二者分开的话这种改变只是在我们的库内部变化，不影响外部使用者。而且还有一个好处是如果产品需求确定下来后，其实是客户端和服务端是可以分别设计业务模型和数据模型的，而不受接口数据结构的左右，这样客户端和服务端都是可以并行工作的。

**Comment by xuyecan** [comment]
### 关于数据结构：

1. 对于struct，我之前有简单看过汇编后的代码，Swift中访问成员变量确实是直接根据偏移量取址，与“C/C++“类似；
2. 对于class，我主要是参考 [Swift ABI的Type Metadata定义描述](https://github.com/apple/swift/blob/master/docs/ABI.rst#type-metadata)，以及Swift源码。文档中明确规定了Metadata的每个结构的布局、涵义。注意 [nominal-type-descriptor](https://github.com/apple/swift/blob/master/docs/ABI.rst#nominal-type-descriptor)，其中有规定`field offset vector`和`field names`、`field type accessor`三个结构，分别表示属性内存起始偏移量、属性名称、属性类型。在HandyJSON最新版本的实现中，主要就是利用这个信息，在反序列时做各个属性的定位，**而不是简单地从前往后移动指针赋值**。所以，即使Swift调整了属性的内存编排，但只要这几个定义保持不变，HandyJSON就不会发生兼容性问题。
3. 关于引用计数。HandyJSON要求class遵循`HandyJSON`协议，要求实现一个`init()`构造函数。所以，在反序列化时，首先会调用这个函数获得一个对象实例，然后再进行赋值。这里其实我们可以分层看：我们可以认为引用计数的概念是在一个高的抽象层次上的，只有在语言层面上的构造、赋值、析构，才会引起引用计数的变化，而HandyJSON的内存赋值是在一个低层次上做的，上层无感知。可以理解为：

```
func deserialize(rawJSON) -> Model {
    let model = Model()

    // do deserialization

    return model
}
```

把关于引用计数无关的部分省略掉，等于就是调用`init()`构造一个堆上的实例，然后返回。中间的内存操作是按照ABI定义去写的，如果写乱了，写到存储引用计数的字段上去，那就是bug了...

### 关于JSON和Model的转化：

我理解，我们现在普遍的服务端和客户端使用JSON传输数据的方案，并不是“客户端模型是依赖于网络传输的JSON结构而定义”。JSON只是我们约定的传输数据的一种协议。一般来说，Model定义是客户端和服务端一起约定的，传输时，根据服务端Model定义序列化得到JSON，客户端再根据一样的定义反序列化得到Model。如果服务端Model定义发生变化，那无论采用哪种协议，本身数据逻辑已经变了，客户端当然也要跟进这个变动的。

打个比方，即使是用PB作为传输协议，当Model定义改变时，也就是IDL文件有变化，编译出两端代码，一样都会产生变化。

说个不太相关的，HandyJSON是支持自定义映射关系的。对于Model的某个字段，你可以给它指定以什么名称去JSON里取值。参考：[自定义解析规则](https://github.com/alibaba/HandyJSON/blob/master/README_cn.md#%E8%87%AA%E5%AE%9A%E4%B9%89%E8%A7%A3%E6%9E%90%E8%A7%84%E5%88%99)
