### ISSUE TITLE
NSManagedObject 不能 toJSON()

### ISSUE THREAD

**Issue by issumao** [alibaba/HandyJSON#121]
拓展 NSManagedObject 并尝试使用 toJSON() 进行序列号，导出为空

**Comment by xuyecan** [comment]
HandyJSON只支持定义在Swift代码里的属性，所有在Objective-C里定义的属性将被忽略。因为内存布局的差异。

比如说，Swift中一个类继承了Objective-C里的父类，并实现了HandyJSON协议，那么，只有Swift中类的属性被处理，父类中的所有属性都会被忽略。
