### ISSUE TITLE
自定义映射和排除操作符提示未知,求解?

### ISSUE THREAD

**Issue by 654691594** [alibaba/HandyJSON#124]
![b8790f7c-a373-4020-b577-72cede18168c](https://cloud.githubusercontent.com/assets/13009430/25221488/d91873c2-25e7-11e7-924c-6fe6eabe0a22.png)
<img width="648" alt="4dfc12fd-6c9b-40bc-9784-a6984b4c5c2e" src="https://cloud.githubusercontent.com/assets/13009430/25221496/e1500636-25e7-11e7-896e-12f097454b2d.png">

**Comment by xuyecan** [comment]
检查下pod里的源码，是否有对应的符号实现呢？是不是引进来的版本没对上？换成 `specify()` 形式就可以吗？

**Comment by xuyecan** [comment]
看报错应该就是版本问题，你换成最新版本试试看。
