### ISSUE TITLE
升级到1.7.1，String的null被解析成"<null>"传入属性中

### ISSUE THREAD

**Issue by HeroBcat** [alibaba/HandyJSON#125]
升级到1.7.1，String类型的API属性，如果返回的是null，这个属性会显示成"<null>"，界面显示变得不符合预期，请问该如何处理？

**Comment by guoguoli** [comment]
oh no! 把服务器返回的 null 解析成<null>了

**Comment by yansun2006** [comment]
我这边也是变成“<null>”了

**Comment by zqy19880909** [comment]
临时解决办法：
在Protocol.swift文件搜索 public static func transform(from object: NSObject) -> String? 这个方法
把最后一句 return "\(object)" 改为 return nil

**Comment by SSSEN** [comment]
突然变“<null>”  zqy19880909 的办法可以解决

**Comment by erepedu** [comment]
+1, null变成"<null>"了

**Comment by xuyecan** [comment]
1.7.2 released。
