### ISSUE TITLE
能不能解析Json数据而不是JsonString数据

### ISSUE THREAD

**Issue by zouxupeng** [alibaba/HandyJSON#128]

**Comment by xuyecan** [comment]
能具体说一下吗？在Swift和ObjectiveC里，JSON数据是用NSDictionary或者NSArray表达的，这个已经支持了。

**Comment by cnxbox360** [comment]
@xuyecan , [Model].deserialized不是只能解析JSONString数据吗？不能解析NSArray吧?

**Comment by CodeKingL** [comment]
我也想问这个问题，后台返回的是json数据，不是Jsonstring ,怎么弄的？

**Comment by DivenLee** [comment]
JSON对象是给JS用的，主要是解决所谓的跨域，这根本不是一个有效的JSON。如果真的需要，可以从逆向思维去试试将数据转换为String的标准格式。@CodeKingL

**Comment by xuyecan** [comment]
@CodeKingL 不太明白你意思呢，”后台返回的JSON数据“，JSON是一个数据格式协议，后台返回JSON数据，总是要有个表达形式的，打个比方，通过http请求获取一段JSON数据，http的body里就是一段JSON格式的二进制数据，用某种字符编码转成字符串，它就是JSON string了。

可能你意思是，你用某个网络库去请求，获取到数据以后，网络已经帮你把数据转换为其他格式了，比如说字典(Alamofire)。HandyJSON支持直接传入字典或者字典数组的。

**Comment by xuyecan** [comment]
@cnxbox360 明白你意思了，我是觉得这一步没必要。。不过后边我可以加上。

HandyJSON现在支持NSDictionary，NSArray只要调用map方法遍历转换一下就ok了，大概是 `NSArray.map{ dict -> return Model.deserializeFrom(dict) }`(伪码)。现在只提供了[接受String的](https://github.com/alibaba/HandyJSON/blob/1c055356a2376013f5f84625974016e74bbfdb16/HandyJSON/Deserializer.swift#L198)，因为String不能直接遍历。

**Comment by xuyecan** [comment]
我新建了一个qq群，可以加群讨论： 581331250。
