### ISSUE TITLE
Manual Installation

### ISSUE THREAD

**Issue by lfarah** [alibaba/HandyJSON#13]
```CocoaPods``` and ```Carthage``` are awesome tools and make our life really easier, but there are some devs who still don't know how to use them. 

It would be cool to add the *Manual installation* guide in your ```README.md```. You can take a look at my [iOS Readme Template](https://github.com/awesome-labs/iOS-readme-template) to see how you can do it.

**Comment by xuyecan** [comment]
Thanks for your advise. I have added the guide in [#dede807](https://github.com/alibaba/HandyJSON/commit/dede807d6182a7a5a5e83b1626b43e90f0e5adbd).
