### ISSUE TITLE
通过JSON对象转换model问题

### ISSUE THREAD

**Issue by chunpingA** [alibaba/HandyJSON#131]
从JSON对象中获取到Dictionary，转换成model，如下所示：

class TestModel: HandyJSON {
    
    var name: String?
    
    var order: NSInteger?
    
    var price: Double = 0
    
    required init () {}
}

转换name是没问题的，但是order和price就有问题了， 在字典中order为NSNumber类型，不能被正常转换。mapping中都是返回对象类型的，不能返回基础数据类型。请问有什么办法能解决吗？

**Comment by xuyecan** [comment]
Swift中`NSInteger`只是`Int`类型的typealias，按道理不会有问题的。请检查下字典中order和price确实为NSNumber类型，或者是格式正确的数字字符串。我这边测试ok的。
