### ISSUE TITLE
请教大神一个关于toJSON的问题

### ISSUE THREAD

**Issue by Mosaics** [alibaba/HandyJSON#133]
如标题所说，当我需要使用toJSON方法的时候，返回的json里面 的value 有可能是optional形的，有没有办法可以直接转成非optionnal的值，这样子就可以直接当网络请求的参数使用了。（除了手动在Struct里自己实现 HandyJSON 协议的 toJSON方法）

**Comment by SoolyChristy** [comment]
可选的guard let 或者 if let 不就行了么。

**Comment by xuyecan** [comment]
我不太明白你意思，请问你是说toJSON以后得到的字符串，可能会出现“optional("sampleString")"这种错误的串吗？如果是这样的话，能否给个sample看下呢？

**Comment by xuyecan** [comment]
还有问题可以进群讨论：581331250。
