### ISSUE TITLE
RealmSwift Object 实现 HandyJSON协议，从数据库取出数据来，toJSONString，toJSON = nil

### ISSUE THREAD

**Issue by csjlengxiang** [alibaba/HandyJSON#138]
RealmSwift Object 实现 HandyJSON协议，从数据库取出数据来，toJSONString，toJSON = nil。

如果只是个 RealmSwift Object 刚创建，可以转换！

**Comment by xuyecan** [comment]
我简单测试了一下没有发现问题，如果你的场景比较复杂，可以贴代码看下。

```swift
class SampleModel: Object, HandyJSON {
    dynamic var id: Int = 0
    dynamic var name: String = ""
}

let model = SampleModel()
model.id = 1
model.name = "ZZ"
let realm = try! Realm()

try! realm.write {
    realm.add(model)
}

let models = realm.objects(SampleModel.self).filter("id = 1")
print(models.toJSONString()!)
print(models[0].toJSONString()!)
```

// it prints:
```
[{"id":0,"name":""},{"id":0,"name":""},{"id":0,"name":""}]
{"id":0,"name":""}
```

可以加群讨论：581331250。

**Comment by csjlengxiang** [comment]
你举例的的代码就有问题啊。

print 的model，json转换都失败了呀，你filter的是 id = 1，可是print的数据，都是默认赋值...我想说的就是这个。

[{"id":0,"name":""},{"id":0,"name":""},{"id":0,"name":""}]
{"id":0,"name":""}


`class SampleModel: Object, HandyJSON {
    dynamic var id: Int = 0
    dynamic var name: String = ""
}

let model = SampleModel()
model.id = 1
model.name = "ZZ"

// 假如你在这个地方 print(model.toJSONString()!) 是可以得到  {"id":1,"name":"ZZ"}
let realm = try! Realm()

try! realm.write {
    realm.add(model)
}

let models = realm.objects(SampleModel.self).filter("id = 1")
print(models.toJSONString()!)
print(models[0].toJSONString()!)`

**Comment by xuyecan** [comment]
。。。
我当时估计有点醉，好的我再看下。

**Comment by csjlengxiang** [comment]
RealmModel的属性是dynamic，于是导致取不出来

**Comment by xuyecan** [comment]
已在 1.8.0 版本中解决，并验证。请测试。

1.8.0版本对于dynamic属性，使用`KVC`处理赋值，不会与Realm冲突。

**Comment by nerd010** [comment]
请问，这个问题现在解决了吗？
Realm + HandyJSON
我在自定义的 class 中继承 Object 时 出现 `Use of undeclared type 'Object'` 这个错误，你们有遇到吗？

**Comment by csjlengxiang** [comment]
解决了的
