### ISSUE TITLE
String数组报错

### ISSUE THREAD

**Issue by pandaApe** [alibaba/HandyJSON#140]
`[String].deserialize(from: arrayJSONString)`

提示：`Type 'String' does not conform to protocol 'HandyJSON'`

ReadMe上说可以直接这么用的啊
> Array<T> // T is one of the above types

**Comment by xuyecan** [comment]
该章节名称是: `Supported Property Type`，意思是支持的字段类型，需要有对象才有字段的概念。`HandyJSON`要求解析的必须为对象，或者对象数组。String并不是对象。

这种类似`["s1", "s2", "s3"]`的简单结构，直接用原生库解析为Array来使用就好啦。
