### ISSUE TITLE
mapping正向与反向的问题

### ISSUE THREAD

**Issue by miws** [alibaba/HandyJSON#142]
mutating func mapping(mapper: HelpingMapper) {
        mapper <<<
            self.orderDetail <-- "T_OrderDetail"
}
这里我指定输入时的规则,但输出时我希望是orderDetail 而不是带T的应该怎么配置呢
即上游给的数据中是使用T_OrderDetail,但我传出给下游时希望使用的是我的字段orderDetail

**Comment by xuyecan** [comment]
暂不支持该特性。
