### ISSUE TITLE
能否支持自动匹配JSON中大写字母开头的word

### ISSUE THREAD

**Issue by action456789** [alibaba/HandyJSON#144]
JSON String：
{
            DeviceDesc = "\U666e\U901a\U706f";
            DeviceMac = "45-fe-D0-E8-41-1A";
            DeviceName = "\U4e3b\U5367\U706f";
            DeviceType = 2;
            RoomID = 7;
            UserID = 11;
}

I need write a lot of code like this：

    func mapping(mapper: HelpingMapper) {
        mapper <<<
            self.deviceDesc <-- "DeviceDesc"
        mapper <<<
            self.deviceMac <-- "DeviceMac"
        mapper <<<
            self.deviceName <-- "DeviceName"
        mapper <<<
            self.dataType <-- "DeviceType"
        mapper <<<
            self.roomID <-- "RoomID"
        mapper <<<
            self.userID <-- "UserID"
    }

Is there a easy way to do this?

**Comment by xuyecan** [comment]
在使用`HandyJSON`前，设置忽略大小写，参考 #65 。

**Comment by action456789** [comment]
赞，支持这个项目，正打算从MJExtentsion全面迁移过来，感谢你们所做的一切！
