### ISSUE TITLE
这种复杂的数据格式怎么处理

### ISSUE THREAD

**Issue by CodeKingL** [alibaba/HandyJSON#148]
我把对应的模型建立好了，但是得不到正确的结果，不知道什么地方出了问题，在你的简书也留言了
{
  "bankTree" : {
    "zhiHangList" : [
      {
        "zhiHang" : {
          "bankOrgId" : "6F1E247962434A2790E205C819CD91C4",
          "parentNo" : 103,
          "identityNo" : 104,
          "name" : "下关支行",
          "role" : "zh"
        },
        "renyuanList" : [
          {
            "bankOrgId" : "59083B3825A344848A70CA3F34648C88",
            "parentNo" : 104,
            "identityNo" : 106,
            "name" : "renxuan（主管）",
            "role" : "zg"
          }
        ]
      },
      {
        "zhiHang" : {
          "bankOrgId" : "6F74C75E9CC841E39C149F9E86E7E300",
          "parentNo" : 103,
          "identityNo" : 105,
          "name" : "建康支行",
          "role" : "zh"
        },
        "renyuanList" : [
          {
            "bankOrgId" : "C36DEBA6987349CC9FBD6A73672D2208",
            "parentNo" : 105,
            "identityNo" : 156,
            "name" : "王台（经理）",
            "role" : "jl"
          }
        ]
      }
    ]
  }
}
需要拿到zhiHang里面的五个值，renyuanList里面的值，感觉我的模型一步步建的不会有问题

**Comment by xuyecan** [comment]
请把你建立的模型和示例字符串提供一下？

**Comment by CodeKingL** [comment]
我建立了三个模型，分别为Test_ZhiListModel，Test_ZhiTitleModel，Test_ZhihangModel。

**Comment by CodeKingL** [comment]
我建立了三个模型，分别为Test_ZhiListModel，Test_ZhiTitleModel，Test_ZhihangModel。
第一个模型里面：
class Test_ZhiListModel: HandyJSON {
    var zhiHangList : [Test_ZhiTitleModel]?
    required init() {}
}
第二个模型：
class Test_ZhiTitleModel: HandyJSON {
    var zhiHang = Test_ZhihangModel()
    required init() {}
}
第三个模型：
class Test_ZhihangModel: HandyJSON {
    var bankOrgId = ""
    var parentNo = 0
    var identityNo = 0
    var name = ""
    var role = ""
    required init() {}
}
示例字符串如下（拷到json解析看下结构就清楚了）：
{
"bankTree" : {
"zhiHangList" : [
{
"zhiHang" : {
"bankOrgId" : "6F1E247962434A2790E205C819CD91C4",
"parentNo" : 103,
"identityNo" : 104,
"name" : "下关机构",
"role" : "zh"
},
"renyuanList" : [
{
"bankOrgId" : "59083B3825A344848A70CA3F34648C88",
"parentNo" : 104,
"identityNo" : 106,
"name" : "renxuan",
"role" : "zg"
}
]
},
{
"zhiHang" : {
"bankOrgId" : "6F74C75E9CC841E39C149F9E86E7E300",
"parentNo" : 103,
"identityNo" : 105,
"name" : "建康机构",
"role" : "zh"
},
"renyuanList" : [
{
"bankOrgId" : "C36DEBA6987349CC9FBD6A73672D2208",
"parentNo" : 105,
"identityNo" : 156,
"name" : "王台",
"role" : "jl"
}
]
}
]
}
}
需要拿到zhiHang里面的五个值，以及renyuanList里面的值

**Comment by xuyecan** [comment]
你的这个类定义：
```
class Test_ZhiListModel: HandyJSON {
    var zhiHangList : [Test_ZhiTitleModel]?
    required init() {}
}
```
其实对应的是`bankTree`这一层节点。所以你designatedPath只需要写到"bankTree"就可以了。

**Comment by xuyecan** [comment]
还有问题可以加群讨论：581331250。
