### ISSUE TITLE
Swift4 Support

### ISSUE THREAD

**Issue by jinfagang** [alibaba/HandyJSON#149]
Seems swift has some issue:
```
/Pods/HandyJSON/HandyJSON/Protocol.swift:179:35: 'Integer' is unavailable
```

**Comment by xuyecan** [comment]
When I want to do the migration to swift 4, I got stuck in a bug similar to this: https://bugs.swift.org/browse/SR-5223. Seems I have to wait for it to be fixed, or an incompatible change will be brought in.

**Comment by xuyecan** [comment]
Luckily I found a better workaround to do the trick. See in this branch: [`dev_for_swift4.0`](https://github.com/alibaba/HandyJSON/tree/dev_for_swift4.0).

But the release version should delay a week or two.
