### ISSUE TITLE
关于字符串解析出<null>的问题

### ISSUE THREAD

**Issue by zixiao0306** [alibaba/HandyJSON#150]
String类型解析会出现"<null>"，这个问题有没有统一的处理方法？

**Comment by DivenLee** [comment]
意思是JSON里没有对应的key，然后出现空字符，而不是nil？对应字段是可选吗？

**Comment by zixiao0306** [comment]
是可选，JSON里面有对应的key，只不过返回的是null，现在被转化成了<null>，描述里面字符串里面本来写的是<null>，提交之后变成了空字符串

**Comment by xuyecan** [comment]
明白你意思，我马上修复这个问题，下午发个新版本。
