### ISSUE TITLE
直接写内存是艺高胆大的艺术行为，有没有审核不过的风险？

### ISSUE THREAD

**Issue by DivenLee** [alibaba/HandyJSON#151]
@xuyecan 真的很优秀的代码，比起Swiftxxx来说实用千百倍。
但是我比较担忧这会不会带来内存的泄露问题，还有Apple会不会拒绝这类应用？
我是用在mac App下，过不了审核的风险呢？

请帮我解答一下这些疑惑，谢谢。

**Comment by xuyecan** [comment]
关于原理和可靠性，参考我之前的一个回复： #116 。

1. 内存泄露。HandyJSON协议要求实现一个空的init()方法，其实这个方法就是代码逻辑的起点。我是先调用init()拿到实例，涉及内存分配、引用计数相关的动作，都是和平常别的代码一样。拿到实例后，这个实例的内存已经在常规的内存管理涵盖之下了，无论后续对这块内存的字段存储区做什么操作，都不会影响内存管理本身。
2. mac APP我没试过，但是iOS上我们用一年多了，没遇到过什么问题，目前也没有听到说反馈不过的情况。实现里调用的都是公开api。

**Comment by DivenLee** [comment]
@xuyecan 非常感谢你们做的一切，这是个很棒的项目，希望能够持续完善和维护它。
