### ISSUE TITLE
请教一下，static 修饰的属性默认是怎么处理的，是忽略了吗

### ISSUE THREAD

**Issue by keepyounger** [alibaba/HandyJSON#152]
定义了一个 static var user 属性，不能通过mapper >>> self.user忽略，想请教一下，是默认忽略 static 修饰的属性吗

**Comment by xuyecan** [comment]
是的，会被忽略。考虑到，static字段不在实例的对象内存里，通过与实例一一对应的JSON数据对它赋值是不合理的，所以目前不提供这个能力。
