### ISSUE TITLE
路径映射

### ISSUE THREAD

**Issue by Mikelulu** [alibaba/HandyJSON#155]
服务器返回{"info": {"count": 4318, "np": 1499661482}
struct ResponseModel: HandyJSON {

//    var info: InfoModel?
    var info_count: Int?
    var info_np: Int?

    var list: [ListModel]?

    mutating func mapping(mapper: HelpingMapper) {

        mapper <<< self.info_count <-- "info.count"
    }
}
为什么这样写 获取不到数据呢

**Comment by xuyecan** [comment]
旧版本不支持，已在 1.8.0 版本支持。请参考：[自定义解析规则](https://github.com/alibaba/HandyJSON/blob/master/README_cn.md#自定义解析规则)。
