### ISSUE TITLE
Model对象可以直接转成OC的对象吗？有什么好的方法？

### ISSUE THREAD

**Issue by zx3570** [alibaba/HandyJSON#156]
未继承NSObject的对象，编译器不会自动转成Objective-C对象，难道要重新解析一遍？请大神指教！

**Comment by xuyecan** [comment]
如果有需要在Objc代码里使用的对象，应该继承NSObject的。你这里遇到什么问题了吗？

**Comment by zx3570** [comment]
明白了，如果要转成Objc对象，模型应该选class，并继承NSObject。struct的话，Objc应该暂时不支持吧？

**Comment by xuyecan** [comment]
对的。并且class中的字段要加上dynamic，不然在Objc中不可见。
