### ISSUE TITLE
toJSON()

### ISSUE THREAD

**Issue by Z-JaDe** [alibaba/HandyJSON#160]
本来想调用toJSON把model对象转换成字典，但是因为对象属性是可选类型，toJSON并没有自动解包， 给服务器传成了Optional("###")，没有可以直接转换成自动解包过的字典的方法吗？
ps：对象属性弄成可选类型是因为有其他用处

**Comment by xuyecan** [comment]
之前，如果属性为数组，是会把数组中的元素转换为可选类型。1.8.0已经修复这个问题。

其他情况，麻烦提供实例类型定义测试。
