### ISSUE TITLE
使用pod根本找到不到HandyJSON

### ISSUE THREAD

**Issue by JoshuaFeng5** [alibaba/HandyJSON#161]
手动导入的话中文版没有解释.....直接看你的demo吧你的source拖入工程也不行..

**Comment by lch872** [comment]
USER_HEADER_SEARCH_PATHS = $(SRCROOT)/Pods  设置了 ?

**Comment by Dengfulei** [comment]
添加了也不行

**Comment by xuyecan** [comment]
运行下`pod repo update`。`HandyJSON`肯定是发布成功的了，我们用都没问题。估计还是你这里环境没对。

pod页面：[`HandyJSON`](https://cocoapods.org/pods/HandyJSON)
