### ISSUE TITLE
手动导入遇到问题

### ISSUE THREAD

**Issue by JoymanM77** [alibaba/HandyJSON#166]
发现了这个数据转模型的库感觉很好用，于是替换了项目已经使用的其他数据转模型的三方库。由于不喜欢使用coocopods，所以选择手动导入。但是在导入的时候不想把xcodeproj拖到自己的项目中，能不能单纯的把有用的文件拖到项目中，但是又分不清哪些是iOS端需要的支持文件，好痛苦。求作者能不能帮忙把你demo里的工程目录重新排列一下，分列清晰一点，谢谢。

**Comment by tom055** [comment]
source文件直接放进去就好 桥接一下就好了

**Comment by xuyecan** [comment]
是的，可以直接把source文件拖到你的工程。也可以考虑用[Carthage](https://github.com/alibaba/HandyJSON#carthage)。
