### ISSUE TITLE
Model update

### ISSUE THREAD

**Issue by trimaximus** [alibaba/HandyJSON#168]
每次解析JSON都会初始化一个Model，能否开放相应的方法，解析JSON更新Model

我修改了一些HandyJSON源码，做了一个BaseModel，但总感觉不科学，对内存机制仅仅了解了皮毛，望解惑

`

    func deserialize(dictionary: NSDictionary) {
        guard let properties = getProperties(forType: type(of: self)) else {
            return
        }
        
        let mapper = HelpingMapper()
        
        let rawPointer: UnsafeMutableRawPointer = UnsafeMutableRawPointer(self.headPointerOfClass())
        var source = dictionary
        if HandyJSONConfiguration.deserializeOptions.contains(.caseInsensitive) {
            let dest = NSMutableDictionary()
            dictionary.allKeys.forEach({ (key) in
                if let sKey = key as? String {
                    dest[sKey.lowercased()] = dictionary[key]
                } else {
                    dest[key] = dictionary[key]
                }
            })
            source = dest
        }
        
        properties.forEach { (property) in
            var key = property.key
            if HandyJSONConfiguration.deserializeOptions.contains(.caseInsensitive) {
                key = key.lowercased()
            }
            let mutablePointer = rawPointer.advanced(by: property.offset)
            if mapper.propertyExcluded(key: mutablePointer.hashValue) {
                return
            }
            
            var maybeValue: Any? = nil
            
            if let mappingHandler = mapper.getMappingHandler(key: mutablePointer.hashValue) {
                if let mappingNames = mappingHandler.mappingNames, mappingNames.count > 0 {
                    for mappingName in mappingNames {
                        if let _value = source[mappingName] {
                            maybeValue = _value
                            break
                        }
                    }
                } else {
                    maybeValue = source[key]
                }
                
                if let transformer = mappingHandler.assignmentClosure {
                    // execute the transform closure
                    transformer(maybeValue)
                    return
                }
            } else {
                maybeValue = source[key]
            }
            
            guard let rawValue = maybeValue as? NSObject else {
                return
            }
            
            if let transformableType = property.type as? _JSONTransformable.Type {
                if let sv = transformableType.transform(from: rawValue) {
                    extensions(of: transformableType).write(sv, to: mutablePointer)
                    return
                }
            } else {
                if let sv = extensions(of: property.type).takeValue(from: rawValue) {
                    extensions(of: property.type).write(sv, to: mutablePointer)
                    return
                }
            }
        }
    }`

**Comment by xuyecan** [comment]
你的建议很赞，我已经在1.8.0添加此功能: [Update Existing Model](https://github.com/alibaba/HandyJSON#update-existing-model)
