### ISSUE TITLE
Deserialize Array Bug

### ISSUE THREAD

**Issue by fede-Raider** [alibaba/HandyJSON#171]
![1](https://user-images.githubusercontent.com/9324985/29464331-da446312-8435-11e7-80ec-df6a92bbccdb.png)
![2](https://user-images.githubusercontent.com/9324985/29464335-dd3a53ce-8435-11e7-86b0-ba72c817d166.png)

Output:
![3](https://user-images.githubusercontent.com/9324985/29464339-e0a2c096-8435-11e7-883a-becf6e31a103.png)

The array c in Cibo is not deserialized.
How can i solve?

**Comment by CiottoliDev** [comment]
What is the output of print(cibo)?

**Comment by CiottoliDev** [comment]
What is the output of `print(cibo!.c)`?

**Comment by fede-Raider** [comment]
Output of "print(cibo!.c)": []
An empty array of SpaceValue

**Comment by xuyecan** [comment]
Essentially, the `Cibo` class is defined as follows(though you give the properties initial values):

```swift
class Cibo: HandyJSON {
    var a: SpaceValue
    var b: SpaceValue
    var c: [SpaceValue]
}
```

And `SpaceValue` is protocol, which means we can't infer the memory layout from its type. So `HandyJSON` just ignore this fields. Generally speaking, deserialization need explicit type information, not just in `HandyJSON`. 

I don't know much about your situation need to do things like this. But Often we can use the [Generics](https://developer.apple.com/library/content/documentation/Swift/Conceptual/Swift_Programming_Language/Generics.html) mechanism to handle it.
