### ISSUE TITLE
关于 HandyJSON 性能的疑问

### ISSUE THREAD

**Issue by KittenYang** [alibaba/HandyJSON#173]
看到一个 Benchmark 评测主流 JSON Object Swift 库性能 https://github.com/bwhiteley/JSONShootout/tree/master， 
 HandyJSON 这种直接写内存的方式应该会比他们快吧？

PS:另外 HandyJSON 不支持 `Int64?` `Int32?`  吗？看这里 https://github.com/alibaba/HandyJSON/blob/master/Tests/HandyJSONTests/BasicTypes.swift 并没有

**Comment by xuyecan** [comment]
性能：`HandyJSON`主要性能损耗在于需要读取内存布局信息，我估计会比主流的库慢一些，但我也没有具体测过。但话说回来，这个库主要是面向移动端开发的，没有过多地考虑性能问题，而是方便优先。对于移动端开发来说，序列化/反序列化通常不会成为性能瓶颈。

Int64/Int32：支持的。参考：https://github.com/alibaba/HandyJSON/blob/master/README_cn.md#支持的属性类型 。类型太多了，测试case中没有写完，后续我继续补上。
