### ISSUE TITLE
didSet不听话

### ISSUE THREAD

**Issue by XFIOSXiaoFeng** [alibaba/HandyJSON#174]
import Foundation
import HandyJSON

struct NearbyListModel: HandyJSON {
    
    // 帖子id
    var tiezi_id : String?
    
    // 用户id
    var account_id : String?
    
    // 发帖人头像
    var icon_url : URL!
    
    // 发帖人昵称
    var user_name : String?
    
    // 帖子标题
    var title : String?
    
    // 帖子内容
    var content : String?
    
    // 帖子配图
    var tiezi_images : [URL]!
    
    // 单张图片宽
    var tiezi_images_width : Float?
    // 单张图片高度
    var tiezi_images_height : Float?

    
    // 保存自动计算得到的高度
    var cellHeight : CGFloat = 0
    
    // 发帖人头像处理
    var thumb_pic : String?{
        didSet{
            guard let thumb_pic = thumb_pic else { return }
            icon_url = URL(string: thumb_pic)
        }
    }
    
    // 缩略图
    var thumb_imgs : [thumb_imgs]?{
        didSet{
            guard let thumb_imgs = thumb_imgs else { return }
            
            tiezi_images_width = Float((thumb_imgs.first?.width)!)
            tiezi_images_height = Float((thumb_imgs.first?.height)!)
            
            for index in 0...thumb_imgs.count {
                guard let url = thumb_imgs[index].url else { return }
                tiezi_images?.append(URL(string: url)!)
            }
        }
    }
didSet不听话，就是不执行里面的方法，搞得我甚是尴尬！！！

**Comment by xuyecan** [comment]
参考：https://github.com/alibaba/HandyJSON/blob/master/README_cn.md#问为什么didsetwillset不好使
