### ISSUE TITLE
后台传null的话  HandyJSON能处理吗

### ISSUE THREAD

**Issue by Keanyuan** [alibaba/HandyJSON#177]

**Comment by xuyecan** [comment]
目前的处理方式是：不给null对应的字段赋值，也就是会跳过这一字段。

**Comment by Keanyuan** [comment]
我这边设定的 var xxx: String?   类型    得到的是一个字符串<null> 这怎么处理

**Comment by Keanyuan** [comment]
我这边设定的 var xxx: String?   类型    得到的是一个字符串<null> 这怎么处理

**Comment by xuyecan** [comment]
你用的是1.8.0版本吗？

**Comment by xuyecan** [comment]
```swift
class Post: HandyJSON {
    var url: String?

    required init() {}
}
```

let jsonStr = "{\"url\":null}"
let mapped = Post.deserialize(from: jsonStr)!
print(mapped.url) // print: nil
print(mapped.toJSONString()!) // print: {}
```
