### ISSUE TITLE
upgraded my project from swfit 3 to swift 4, Error in version 4.0.0 and Xcode 9.0

### ISSUE THREAD

**Issue by turkeyaa** [alibaba/HandyJSON#185]
I recently upgraded my project from swift 3 to swift 4 and during the migration, the HandyJSON has been given me one error in this:

protocol IntegerPropertyProtocol: Integer, BuiltInBasicType {
init?( text: String, radix: Int)
init(_ number: NSNumber)
}

Xcode Prompt solution：'Integer' has been renamed to 'BinaryInteger'/Replace 'Integer' with 'BinaryInteger'

**Comment by vicky1221** [comment]
I have the same problem. Please solve it

**Comment by xuyecan** [comment]
Please upgrade HandyJSON to [4.0.0-beta.1](https://github.com/alibaba/HandyJSON#installation) version which has solved the compiling issues on Swift 4.0.
