### ISSUE TITLE
小问题

### ISSUE THREAD

**Issue by Z-JaDe** [alibaba/HandyJSON#20]
能不能写一个把model转换成字典或者数组的方法，有时候可能会用到.为什么类里面要实现这个required init() {}.

**Comment by Z-JaDe** [comment]
还有能不能把model转换成字典或者数组，有时候可能会用到

**Comment by Z-JaDe** [comment]
为什么类里面要实现这个required init() {}，如果我在父类init()里面写了一些东西，子类里面不再写required init() {}可不可以

**Comment by xuyecan** [comment]
1. 这个功能已经在开发中了，下个版本就会支持；
2. `JSONDeserializer<T: HandyJSON>.deserializeFrom(json: <String>)`  方法，做的第一件事情便是：根据`T`类型来生成一个初始实例，这个过程便是调用了 `let instance = T.init()`。Swift中，`class`类型默认实现了空的`init()`构造函数，但一旦你为它指定了别的构造函数，这个空的就会被覆盖。所以协议中就要求必须显式实现一个空的，以便 `let instance = T.init()` 能够成功执行。

**Comment by Z-JaDe** [comment]
哦，原来是这样，那我如果在父model中实现了init方法，子model中就没必要再写一遍了吧

**Comment by xuyecan** [comment]
还是需要的，因为要拿到子model的实例，仍然需要子model指定一个构造函数。
