### ISSUE TITLE
为什么字典转模型时 传参数是 ObjectC 的 NSDictionary 类型 而不是 Swift 的 Collection 类型

### ISSUE THREAD

**Issue by missyouguys** [alibaba/HandyJSON#21]
为什么 里面的实现 都是 用 的 Object-C 的 NSDictionary. NSArray  而不是 swift 的 Collection 呢
似乎也没有 Array -> Model

**Comment by xuyecan** [comment]
1. 对于`deserializeFrom()`接口，目前确实只接受 string类型的json串 和 NSDictionary，后续会增加对 Swift的Dictionary<String, AnyObject>的支持。
2. 如果是Model类里的属性类型，那 NSDictionary、NSArray、Dictionary<String, AnyObject>、Array<AnyObject> 都是支持的呀。

**Comment by xuyecan** [comment]
此外，Array -> Model，感觉没有这种场景吧，还是你说的是 Array<String> -> Array<Model>呢？一个数组没办法映射到一个Model上的，因为Model对应的是KV结构的collection。
