### ISSUE TITLE
Support Linux

### ISSUE THREAD

**Issue by hikelee** [alibaba/HandyJSON#22]
I want to use it in server side, can this project support Linux？

**Comment by xuyecan** [comment]
Refer to this page:
>... Swift on Linux does not depend on the Objective-C runtime nor includes it. While Swift was designed to interoperate closely with Objective-C when it is present, it was also designed to work in environments where the Objective-C runtime does not exist. ...

It means that much code relate to Objective-C runtime in this project can not run on linux. All this code is to support the Apple Platforms. So the answer is no.

On the good side, `HandyJSON` should work on linux after removing the code run in Objective-C runtime. We are considering release a pure swift version to support linux.

**Comment by issumao** [comment]
Really looking forward to the Linux version!
