### ISSUE TITLE
请问有json数组转模型数组的方法么?

### ISSUE THREAD

**Issue by Pr-Chen** [alibaba/HandyJSON#23]
请问有json数组转模型数组的方法么?

**Comment by xuyecan** [comment]
此功能已经列在[To Do](https://github.com/alibaba/HandyJSON#to-do)中，即`Support non-object (such as basic type, array, dictionany) type deserializing directly`。我们正在开发，预计下个版本支持。

现在如果需要这个能力，可以先使用系统库把json反序列化为字典数组，然后遍历数组，使用`deserializeFrom(dict: NSDictionary)`把数组里的字典转换为Model。

**Comment by Pr-Chen** [comment]
嗯,期待...👍这是我见过的最好用的swift json转模型的库了.
