### ISSUE TITLE
内存泄漏

### ISSUE THREAD

**Issue by EJunYan** [alibaba/HandyJSON#232]
//  数据模型
class TestListModel: HandyJSON {
    var address: String?
    var id: Int?
    var title: String?
    var state: Int?
    required init() {}
}

class GetTest: HandyJSON {
    var errcode: Int?
    var errmsg: String?
    var interestPointList: [TestListModel] = []
    required init() {}
}

// 测试代码
        let t = """
{\"errcode\":0,\"errmsg\":\"获取兴趣点列表成功\",\"interestPointList\":[{\"address\":\"韶关市始兴县马市镇\",\"id\":60,\"state\":0,\"title\":\"测试数据更新\"},{\"address\":\"深圳市南山区沙河街道华夏路93号沙河工业区东区\",\"id\":61,\"state\":0,\"title\":\"诛仙和感受\"}]}
"""
let s =  GetTest.deserialize(from: t)

**Comment by memoriesofsnows** [comment]
https://user-images.githubusercontent.com/17523689/32884397-2470996e-caf5-11e7-8736-ddb0f9e21da6.png
如图，在Measuable文件添加这两条代码即可。

**Comment by EJunYan** [comment]
好的问题解决
