### ISSUE TITLE
Xcode 9.3 beta 调用handyjson 崩溃

### ISSUE THREAD

**Issue by wzwc456** [alibaba/HandyJSON#234]
pointer.pointee 调用崩溃

**Comment by spicyShrimp** [comment]
同上,我也是遇到相同调用崩溃
Swift4.0 项目正常运行
Swift4.1 项目运行调用就崩溃了
崩溃pointer.pointee

**Comment by BlackXzq** [comment]
同上,我也是遇到相同调用崩溃
Swift4.0 项目正常运行
Swift4.1 项目运行调用就崩溃了
崩溃pointer.pointee

**Comment by xuyecan** [comment]
Fixed in #245 . And 4.1.0 released.
