### ISSUE TITLE
Xcode9.3 Swift4.1 crash 解决方案

### ISSUE THREAD

**Issue by GorXion** [alibaba/HandyJSON#239]
![default](https://user-images.githubusercontent.com/15857442/38131166-9f3d334e-3438-11e8-94a3-4d39c083344c.png)
如图修改

**Comment by iWECon** [comment]
如出现低版本无法使用，请按照如下方法修改：
`
#if swift(>=4.1)
    return ......... base.pointee - base.hasValue)
#else
    return 原始内容
#endif
`

**Comment by hh1myfei** [comment]
@iWECon  怎样获得语言的版本号、

**Comment by iWECon** [comment]
@hh1myfei XCode 9.3 Swift 4.1 中引入 
`#if swift(>=4.1)`

**Comment by koalahl** [comment]
👍

**Comment by xuyecan** [comment]
Fixed in #245 . And 4.1.0 released.
