### ISSUE TITLE
Xcode 9.3 Swift 4.1 crash

### ISSUE THREAD

**Issue by Tommynocker** [alibaba/HandyJSON#240]
Crash in NumberofFields

<img width="1040" alt="bildschirmfoto 2018-03-30 um 17 56 23" src="https://user-images.githubusercontent.com/37936367/38144087-b0393232-3443-11e8-97d5-c35facc171f3.png">

**Comment by AmyF** [comment]
[https://github.com/alibaba/HandyJSON/issues/239](url)
这里暂时解决了这个问题。

**Comment by Tommynocker** [comment]
works, thanks

**Comment by juliancadi** [comment]
@Tommynocker what is the workaround to this? @AmyF 's URL seems to be broken (https://github.com/alibaba/HandyJSON/issues/239). What is the temporary solution?

**Comment by JasonSparrow** [comment]
更新了xcode 9.3, Swift4.1  numberOfFields crash 该怎么解决?

**Comment by MoennigQ** [comment]
怎么解决的？https://github.com/alibaba/HandyJSON/issues/239链接无效

**Comment by AmyF** [comment]
解决方法在这里#239

**Comment by AmyF** [comment]
解决方法在这里 #239 
@MoennigQ @JasonSparrow

**Comment by xuyecan** [comment]
Fixed in #245 . And 4.1.0 released.
