### ISSUE TITLE
Maintain HandyJSON

### ISSUE THREAD

**Issue by levanlongktmt** [alibaba/HandyJSON#241]
Hi everyone who love this library. Seemly this repository has been abandoned. So I had forked this project to https://github.com/levanlongktmt/HandyJSON and apply code for fix some bugs in pull requests of current repository. I will maintain this project in my repository. But Im not iOS master, so I hope every one can help me. Thanks.

I don't know Chinese, so please using English ^^.

--Edit--

Please create Issues and PR to repository in https://github.com/levanlongktmt/HandyJSON. Because Im not owner of repository alibaba/HandyJSON, so I cannot commit, fix, apply new code in this repository.

**Comment by JasonSparrow** [comment]
Thank you very much to continue to maintain the project.

**Comment by SonNguyen177** [comment]
many thanks, Long.

**Comment by CodeKingL** [comment]
Sorry, I would like to say that the author of this library has suspended the update for work reasons, but it is not that no one has been updated. I hope you can promote it, but don't do the copyright infringement thing.

对不起，我想说下，这个库的作者因为工作原因暂停更新，但不是没人更新，希望你可以发扬，但是不要做侵犯版权的事情
