### ISSUE TITLE
关于HandyJSON在swift4.1报错以及后续更新问题

### ISSUE THREAD

**Issue by CodeKingL** [alibaba/HandyJSON#243]
最近大家更新swift4.1之后多多少少出了一些问题，不过问题有大神已经解决，并且经过验证确实可行，希望大家暂时按照解决方案解决；对于比较关心的更新问题，我在联系作者，可能因为作者那边比较忙，暂时没有回复，希望大家还是可以继续支持，有消息会及时通知大家。此外，QQ群人数已满，节后我看下开一个2群，到时候把群号贴出来（现在的群是由作者建立的，我是管理，所以后面建立2群的话，一样的性质）

**Comment by aasdsjk** [comment]
@CodeKingL 我还在想为什么没有同意我的加群申请，原来是人满了

**Comment by xuyecan** [comment]
是我跟进太迟钝了，感谢 @CodeKingL 。现在4.1issue已经fixed，QQ群也已经升级。

后续我会多设置几个管理员，避免我成为单点。抱歉抱歉。

**Comment by h242799999** [comment]
问题还有，，我已经更新 4.1.0了

**Comment by h242799999** [comment]
<img width="867" alt="qq20180408-204337 2x" src="https://user-images.githubusercontent.com/13128028/38467597-9fab717e-3b6d-11e8-8ecf-11849c447de3.png">
问题还有，，我已经更新 4.1.0了

**Comment by xuyecan** [comment]
@h242799999 你用的是swift3.3吧？更新到4.1.1。4.1.0漏掉了swift3.3的情况。

**Comment by zxm9988** [comment]
4.1.1 也有同样的问题

**Comment by zxm9988** [comment]
<img width="402" alt="hand" src="https://user-images.githubusercontent.com/1468865/38603850-52f365a4-3da1-11e8-8afb-d2b66a71ed3c.png">
确定使用的swift 4.1

**Comment by CodeKingL** [comment]
现在已经更新，请查看最新版本，有问题可以进群交流


愿你我既可以朝九晚五，又可以浪迹天涯！
在2018年04月11日 16:00，肖邦强 写道：

确定使用的swift 4.1
