### ISSUE TITLE
在swift3.3 使用1.8.0版本崩溃 Xcode9.3

### ISSUE THREAD

**Issue by guojianfeng01** [alibaba/HandyJSON#246]

**Comment by guojianfeng01** [comment]
赶紧看一下

**Comment by codeRiding** [comment]
/*
        #if swift(>=4.1)
        return NominalTypeDescriptor(pointer: relativePointer(base: base, offset: base.pointee - base.hashValue))
        #else
        return NominalTypeDescriptor(pointer: relativePointer(base: base, offset: base.pointee))
        #endif
        */
        
如果是swift3.3结合xcode9.3出现问题，将上面的代码换成如下

        return NominalTypeDescriptor(pointer: relativePointer(base: base, offset: base.pointee - base.hashValue))

**Comment by codeRiding** [comment]
或者改成大于swift3.3


#if swift(>=3.3)
return NominalTypeDescriptor(pointer: relativePointer(base: base, offset: base.pointee - base.hashValue))
#else
return NominalTypeDescriptor(pointer: relativePointer(base: base, offset: base.pointee))
#endif

**Comment by xuyecan** [comment]
@codeRiding 直接改成  swift(>=3.3) 会把4.0包含进去。

参考：https://github.com/alibaba/HandyJSON/commit/a9badf0f26af6d7bf9aaa5f6b6dde4e343533b85

已发布： 4.1.1
