### ISSUE TITLE
请问下一个版本大概什么时候能发布呢?

### ISSUE THREAD

**Issue by Pr-Chen** [alibaba/HandyJSON#27]

**Comment by cijianzy** [comment]
不出意外应该快了，作者已经完成了序列化成字典功能，现在还缺基础类型的反序列化，应该在两周之内。

**Comment by xuyecan** [comment]
计划这周末。顺便问下，你对新功能上有什么要求或者建议吗？

**Comment by Pr-Chen** [comment]
期待半个月了，终于要发布了。感谢你的成果。目前需要的功能不复杂，所以还没有什么建议。希望以后自己能为这个库做贡献。

**Comment by xuyecan** [comment]
嗯，我才记起来上次是你提出issue希望支持json数组直接转换为模型数组，这里我有点疑惑，你说的json数组，是指json字符串数组呢，还是[NSDictionary]这样的数组？

我即将要发布的版本主要是支持 Model 序列化为 字典，即 issue [#20](https://github.com/alibaba/HandyJSON/issues/20) 中提到的。

所以我希望明确一些知道你的需求，我好好考虑怎么一起做进去~

**Comment by Pr-Chen** [comment]
就像YYModel中的`+ (nullable NSArray *)yy_modelArrayWithClass:(Class)cls json:(id)json;`，或者MJExtension中的`+ (NSMutableArray *)mj_objectArrayWithKeyValuesArray:(id)keyValuesArray;`这种。

**Comment by xuyecan** [comment]
了解了。其实这种情况下，遍历一遍生成并不会麻烦多少。。

真让我纠结的是 [{"key1":"value1"}, {"key2": "value2"}] 这种json串的反序列化。同样是一个字符串，它反序列化的结果是一个数组。也就是说，我还需要提供一个 `deserializeFrom(json: String) -> Array<T>` 方法，和原来的只有返回值不一样。这就导致接口变得很难懂。想来想去，我还是先不支持这种情况。

至于你这种场景下需要的 `deserializeFrom(jsonDictArray: Array<NSDictionary>) -> Array<T>` 方法和 `deserializeFrom(jsonArray: Array<String>) -> Array<T>` 方法，我今晚一起加一下，然后发布~

**Comment by xuyecan** [comment]
纠结了一个晚上，本来想针对你这种场景加下面两个方法的：

```
public static func deserializeFrom(jsonArray: Array<String>) -> Array<T?> {
    return jsonArray.map({ (json) -> T? in
        return deserializeFrom(json: json)
    })
}

public static func deserializeFrom(dictArray: Array<NSDictionary>) -> Array<T?> {
    return dictArray.map({ (dict) -> T? in
        return deserializeFrom(dict: dict)
    })
}
```

但想想其实只是封装了一句调用，意义不是特别大，反而弄得接口不太清晰了。。所以我暂时还是不加了，你可以参考实现下。我加的方法是处理 "[{"key1":"value1"}, {"key2": "value2"}]" 这种json的，感觉这个才有必要。

**Comment by Pr-Chen** [comment]
好吧，貌似是我说错了，我需要的就是你的这种"[{"key1":"value1"}, {"key2": "value2"}]" 。
