### ISSUE TITLE
Xcode8.1编译报错

### ISSUE THREAD

**Issue by Hanwp** [alibaba/HandyJSON#28]
/Pods/HandyJSON/HandyJSON/**Property.swift:404**:86: Cannot assign to property: 'pointee' is a get-only property

**Comment by aixinyunchou** [comment]
me too

**Comment by aixinyunchou** [comment]
#29  fix this

**Comment by Hanwp** [comment]
@aixinyunchou cocoapods上没有更新吗？我是用cocoapods管理的，该怎么解决这个问题。

**Comment by xuyecan** [comment]
发布1.2.0解决这个问题了~ 感谢 @aixinyunchou !

引入： `pod 'HandyJSON', '~> 1.2.0'`
