### ISSUE TITLE
handyJson使用dev_for_swift4.2分支之后，仍然crash

### ISSUE THREAD

**Issue by rainymoodone** [alibaba/HandyJSON#283]
![image](https://user-images.githubusercontent.com/18651527/45477015-18344180-b773-11e8-8d8a-53b88512d4c6.png)

**Comment by lynnleelhl** [comment]
你用的 xcode 版本是？

**Comment by rainymoodone** [comment]
> 你用的 xcode 版本是？

10 beat6

**Comment by lynnleelhl** [comment]
信息再给多一点，跑的是什么工程，什么设备上跑的，最好直接给个demo

**Comment by idododo** [comment]
library not found for -lstdc++.6.0.9

**Comment by lynnleelhl** [comment]
给个demo吧，我无法复现你们说的问题

**Comment by rainymoodone** [comment]
[HandyJsonTest.zip](https://github.com/alibaba/HandyJSON/files/2382484/HandyJsonTest.zip)

**Comment by rainymoodone** [comment]
> 给个demo吧，我无法复现你们说的问题

使用的是xCode10-beat6，模拟器是iPhone8 plus(12.0)，（抱歉，昨天改其他问题，没来的急）
[HandyJsonTest.zip](https://github.com/alibaba/HandyJSON/files/2382489/HandyJsonTest.zip)
