### ISSUE TITLE
Xcode10: Can't build framework via carthage.

### ISSUE THREAD

**Issue by shroff-kandarp** [alibaba/HandyJSON#285]
Your project does not Compile.

*** Checking out HandyJSON at "4.1.3"
*** xcodebuild output can be found in /var/folders/5h/yvpgl5hs105fhhy7g2sw6hym0000gn/T/carthage-xcodebuild.YTROrU.log
*** Building scheme "HandyJSON iOS" in HandyJSON.xcodeproj
Build Failed
	Task failed with exit code 65:
	/usr/bin/xcrun xcodebuild -project /Users/shrey/Documents/Tmp/Carthage/Checkouts/HandyJSON/HandyJSON.xcodeproj -scheme HandyJSON\ iOS -configuration Release -derivedDataPath /Users/shrey/Library/Caches/org.carthage.CarthageKit/DerivedData/10.0_10L201y/HandyJSON/4.1.3 -sdk iphoneos ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES archive -archivePath /var/folders/5h/yvpgl5hs105fhhy7g2sw6hym0000gn/T/HandyJSON SKIP_INSTALL=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=NO CLANG_ENABLE_CODE_COVERAGE=NO STRIP_INSTALLED_PRODUCT=NO (launched in /Users/shrey/Documents/Tmp/Carthage/Checkouts/HandyJSON)

This usually indicates that project itself failed to compile. Please check the xcodebuild log for more details: /var/folders/5h/yvpgl5hs105fhhy7g2sw6hym0000gn/T/carthage-xcodebuild.YTROrU.log

**Comment by jh235** [comment]
pod 'HandyJSON', :git => 'https://github.com/alibaba/HandyJSON.git', :branch => 'dev_for_swift4.2'

**Comment by lynnleelhl** [comment]
Please try 4.2.0
