### ISSUE TITLE
Xcode10编译报错

### ISSUE THREAD

**Issue by haitao642** [alibaba/HandyJSON#287]
报了这两个错误，哪位大神解释下
<img width="404" alt="qq20180918-175533 2x" src="https://user-images.githubusercontent.com/10614775/45679938-47c8bc80-bb6c-11e8-9b7d-3729b67356be.png">
<img width="722" alt="qq20180918-175550 2x" src="https://user-images.githubusercontent.com/10614775/45679946-4a2b1680-bb6c-11e8-95c4-837f1ca8d86c.png">

**Comment by lynnleelhl** [comment]
4.2.0 版本试下
