### ISSUE TITLE
xcode10.0正式版-swift4报错

### ISSUE THREAD

**Issue by WillieWu** [alibaba/HandyJSON#288]
使用HandyJSON 4.1.3。
请问好久可以更新呢？
报错见下
![error-1](https://user-images.githubusercontent.com/8049894/45680066-95452980-bb6c-11e8-8bb6-384517fb5a7d.jpg)
![error-2](https://user-images.githubusercontent.com/8049894/45680071-99714700-bb6c-11e8-8d33-ac18fddee937.jpg)

**Comment by lynnleelhl** [comment]
使用 dev_for_swift4.2 分支

**Comment by lhkzhl** [comment]
pod 'HandyJSON', '~> 4.2.0-beta1'

**Comment by lhkzhl** [comment]
哈哈 有谢谢我的吗？我也是菜B

**Comment by U7426** [comment]
@lhkzhl 谢谢

**Comment by lynnleelhl** [comment]
@lhkzhl 谢谢

**Comment by WillieWu** [comment]
6 @lhkzhl

**Comment by gy37** [comment]
已解决，O(∩_∩)O谢谢

**Comment by xiaozhi** [comment]
谢谢~

**Comment by lhkzhl** [comment]
pod update HandyJSON     
4.2正式版已经出了，就别用beta版的啦
