### ISSUE TITLE
pod update 之后报错了，是新版本兼容问题吗

### ISSUE THREAD

**Issue by cavanlee** [alibaba/HandyJSON#297]
Undefined symbols for architecture x86_64:
  "_swift_getFieldAt", referenced from:
      HandyJSON.Metadata.Class._propertyDescriptionsAndStartPoint() -> ([HandyJSON.Property.Description], Swift.Int32?)? in Metadata.o
      HandyJSON.Metadata.Struct.propertyDescriptions() -> [HandyJSON.Property.Description]? in Metadata.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by jaderYang** [comment]
xcode 9+ 用4.1.1+
xcode 10+ 用4.2.0+

**Comment by meifu1709** [comment]
请问兼容swift5了吗？更新后也报错了
Undefined symbols for architecture x86_64:
  "_swift_getFieldAt"

**Comment by ChardXu** [comment]
Xcode10 用的4.2 ，同样报这个错 @jaderYang

**Comment by lostpupil** [comment]
大噶 用 5.0 dev 的那个分支 就可以解决了。

**Comment by wty302857194** [comment]
Xcode 更新以后报错

**Comment by yugaoxiang** [comment]
解决了吗。大佬们

**Comment by lynnleelhl** [comment]
Xcode 10.2 "5.0.0-beta.1"
