### ISSUE TITLE
Undefined symbols  "_swift_getFieldAt"

### ISSUE THREAD

**Issue by miku1958** [alibaba/HandyJSON#307]
试了一下Xcode 10.2,编译提示:
Undefined symbols for architecture x86_64:
  "_swift_getFieldAt", referenced from:
      HandyJSON.Metadata.Class._propertyDescriptionsAndStartPoint() -> ([HandyJSON.Property.Description], Swift.Int32?)? in Metadata.o
      HandyJSON.Metadata.Struct.propertyDescriptions() -> [HandyJSON.Property.Description]? in Metadata.o

尝试把pod项目中swift version改成4.2也是一样

**Comment by lynnleelhl** [comment]
Swift 5 removed swift_getFieldAt, I'm working on it. 
You can use Xcode 10.1 or previous version.

**Comment by lynnleelhl** [comment]
Branch dev_for_swift5.0 solved this.

**Comment by jiang443** [comment]
XCode10.2 使用Swift5.0已经发布。    请尽快适配。

**Comment by WhoJave** [comment]
今天好多人因为这个加群的~ 慢慢适配 我们就可以折腾下自己的事儿了

**Comment by lynnleelhl** [comment]
pod 'HandyJSON', '5.0.0-beta'

**Comment by jeffreylyg** [comment]
如果是 swift 5 编译不过还能理解，为什么 Xcode 10.2 选 4.2 编译还报这个错呢？Xcode 10.1 用 4.2编译就没问题

**Comment by lynnleelhl** [comment]
@jeffreylyg 你在 Build Settings 里面选择的 Swift 版本并不是编译用的 Swift 版本，你可以终端跑下 `swift --version` 会发现返回的还是 5.0

**Comment by cjsliuj** [comment]
> @jeffreylyg 你在 Build Settings 里面选择的 Swift 版本并不是编译用的 Swift 版本，你可以终端跑下 `swift --version` 会发现返回的还是 5.0

那  Build Settings 里面的 SWIFT_VERSION 是啥意思呢？

**Comment by skytodmoon** [comment]
> @jeffreylyg 你在 Build Settings 里面选择的 Swift 版本并不是编译用的 Swift 版本，你可以终端跑下 `swift --version` 会发现返回的还是 5.0

我机器显示的是swift4.2.1，也有该问题

**Comment by skytodmoon** [comment]
从10.1 swift4.2升级到11.2 swift 2遇到同样问题

**Comment by lynnleelhl** [comment]
@skytodmoon HandyJSON 用最新版本
