### ISSUE TITLE
泛型解析nil,希望能尽快解决啊

### ISSUE THREAD

**Issue by 429329513wanting** [alibaba/HandyJSON#314]
🍀============APP RESPONSE:
{
  "data" : [
    {
      "sortNo" : 1,
      "deleted" : "F",
      "id" : 10,
      "imageLink" : "",
      "imageUrl" : "\/static\/data\/appimage\/\/fileupload\/20190214\/2019021415314269dmm7.png",
      "imageType" : "1",
      "imageName" : "默认轮播图1",
      "projectId" : 3
    }
  ],
  "status" : 200,
  "success" : true
}
(lldb) po base
▿ ALNetHTTPResponseArray<WelComVo>
  - status : 200
  - error : nil
  - errorMsg : nil
  - success : true
  - data : nil

**Comment by 429329513wanting** [comment]
HTTPRequestManager.GETRequest(url:Constant.Welcom,parameter:params) {
                                                    (response:ALResult<ALNetHTTPResponseArray<WelComVo>>) in
        
            guard response.isSuccess else{
                
                success([WelComVo()])
                return
                
            }
            let base :ALNetHTTPResponseArray<WelComVo> = response.value!
            success(base.result as Any)
        }

**Comment by mikeooye** [comment]
同时安装回了 Xcode 10.1，设置 Command Line Tools 为 Xcode 10.1 用于打包，先用低版本吧。

**Comment by 429329513wanting** [comment]
> 同时安装回了 Xcode 10.1，设置 Command Line Tools 为 Xcode 10.1 用于打包，先用低版本吧。
