### ISSUE TITLE
xcode 10.2 release问题

### ISSUE THREAD

**Issue by leafM3** [alibaba/HandyJSON#319]

**Comment by leafM3** [comment]
大神，请教一下
pod 'HandyJSON', git:"https://github.com/alibaba/HandyJSON.git",branch:"5.0.0-beta.1"
调试状态没有任何问题，一旦release发包，就发现解析不到数据对象。
求指教～用了泛型。😢

**Comment by leafM3** [comment]
由其他原因引起，关闭，谢谢！

**Comment by tzongw** [comment]
请问是什么原因引起的呢，我也遇到类似的问题，debug模式下一切正常，release模式很多奇怪错误，比如说Int类型的字段为0

**Comment by 20120608** [comment]
这是因为Swift的debug和release模式下的编译优化级别是不同的。

在debug模式下，Swift编译器的优化级别很低，主要是为了保证代码的调试性，使得代码行为更加可预测，更容易进行调试。在这种情况下，即使你的模型属性是用let声明的，HandyJSON可能也能正确地解析JSON并赋值给这些属性，因为编译器在这种模式下不会对这些行为进行过多的优化和干预。

然而，在release模式下，Swift编译器的优化级别会提高，以提高代码的运行效率和性能。在这种模式下，编译器可能会更加严格地遵守Swift的语义规则，因此不允许对let声明的常量进行修改。这就可能导致HandyJSON在尝试修改这些属性时失败，从而导致解析错误。

因此，如果你的模型需要被HandyJSON或其他类似的库修改，你应该使用var而不是let来声明你的模型属性。这样可以确保你的代码在debug和release模式下都能正确地工作。

**Comment by leafM3** [comment]
您好！您的邮件，我已经收到！  我将尽快答复您！  祝， 好！－－－－－－－－－－－－－－－－－－－－－－－－－－－－  Dear ！I have received your message！  I'll get back to you as soon as possible!  Best wishes!
