### ISSUE TITLE
如何应对服务端和前端命名不一致的问题？

### ISSUE THREAD

**Issue by roshanman** [alibaba/HandyJSON#34]
我们项目中的服务端使用nodejs编写，开发人员习惯用下划线命名比如result_code，有下划线并且都是小写，这就和swift的命名不一致，请问怎么处理？

**Comment by Pr-Chen** [comment]
func mapping(mapper: HelpingMapper) {
        // specify 'cat_id' field in json map to 'id' property in object
        mapper.specify(property: &id, name: "cat_id")
    }

**Comment by xuyecan** [comment]
如 @Pr-Chen 所答，在定义 `class` 或者 `struct` 时，除了实现 `HandyJSON` 以外，再实现一个 `func mapping(mapper: HelpingMapper)` 函数，在里边指定解析每一个字段在 `json` 中的字段名。
见 https://github.com/alibaba/HandyJSON#custom-mapping 。
