### ISSUE TITLE
请问如何更新到 5.0.2-beta 这个版本？

### ISSUE THREAD

**Issue by uclort** [alibaba/HandyJSON#369]
podfile 文件中 pod 'HandyJSON', '~> 5.0.1', 直接 pod update HandyJSON 找不到新版本，pod search HandyJSON 可以看到 5.0.2-beta 这个版本。

**Comment by xiaolouxinyue** [comment]
pod 'HandyJSON', '~> 5.0.2-beta'

**Comment by xiaobadao** [comment]
> pod 'HandyJSON', '~> 5.0.2-beta'

你这个不管用呀。他还会更新到 5.0.1上去的。

**Comment by nlnlnull** [comment]
> > pod 'HandyJSON', '~> 5.0.2-beta'
> 
> 你这个不管用呀。他还会更新到 5.0.1上去的。

pod 'HandyJSON', '5.0.2-beta' 
我是这么解决的，还不行的话更新一下本地库。

**Comment by shang1219178163** [comment]
更新 5.0.1 然后把 5.0.2 压缩包下载替换里边的文件即可

> podfile 文件中 pod 'HandyJSON', '~> 5.0.1', 直接 pod update HandyJSON 找不到新版本，pod search HandyJSON 可以看到 5.0.2-beta 这个版本。

更新 5.0.1 然后把 5.0.2 压缩包下载替换里边的文件即可

**Comment by shang1219178163** [comment]
> podfile 文件中 pod 'HandyJSON', '~> 5.0.1', 直接 pod update HandyJSON 找不到新版本，pod search HandyJSON 可以看到 5.0.2-beta 这个版本。

更新 5.0.1 然后把 5.0.2 压缩包下载替换里边的文件即可,git 包本质还是文件的上传，本身源文件和 git 没关联
