### ISSUE TITLE
Crash at iOS 14 beta 4

### ISSUE THREAD

**Issue by CodeEagle** [alibaba/HandyJSON#395]
![image](https://user-images.githubusercontent.com/2311352/89379278-1ccbbf80-d728-11ea-93f8-d03a6c58d0d5.png)

**Comment by liuzhuoming** [comment]
@lynnleelhl  SOS

**Comment by lynnleelhl** [comment]
https://github.com/alibaba/HandyJSON/pull/397
This PR should solve the problem, but still need full test until merge

**Comment by lynnleelhl** [comment]
try 5.0.3-beta

**Comment by Liaoworking** [comment]
same issue here.

**Comment by RoganZheng** [comment]
We need a official version which solve this problem as soon as possible.

**Comment by lkkwxy** [comment]
> We need a official version which solve this problem as soon as possible.

@lynnleelhl

**Comment by shenglinFL** [comment]
> try 5.0.3-beta

https://github.com/apple/swift/pull/33319/files

This problem may not need to be solved?

**Comment by qinling01** [comment]
期待修复后的正式版出来
![C682B8B2-6613-48F3-BC4E-F53BCCF38725](https://user-images.githubusercontent.com/17538968/89992297-a98df480-dcb7-11ea-860b-bef9a6954b86.png)

**Comment by shuyujin** [comment]
期待解决

**Comment by wwy0918** [comment]
+1

**Comment by WZBbiao** [comment]
iOS 14 Beta5 seems to fix this problem
