### ISSUE TITLE
升级到'HandyJSON', '5.0.3-beta'，对象内有参数为nil，调用.toJSONString()，crash

### ISSUE THREAD

**Issue by zhengzhong5127** [alibaba/HandyJSON#399]
Fatal error: Unexpectedly found nil while unwrapping an Optional value: file /Users/***/Documents/Work/***/Pods/HandyJSON/Source/ExtendCustomModelType.swift, line 77

**Comment by shenglinFL** [comment]
确认升级5.0.3-beta了吗？

**Comment by zhengzhong5127** [comment]
是的，为了适配iOS14beta版本，升级到5.0.3-beta之后，14的crash没了，但是依旧崩溃，提示就是我上面贴的错误

**Comment by zhengzhong5127** [comment]
sorry, 可能上午我的本地有缓存，并没有更新到最新版本。刚clean了一下，又update之后可以了。麻烦了。
