### ISSUE TITLE
Undefined symbols for architecture i386:

### ISSUE THREAD

**Issue by yanjinquan** [alibaba/HandyJSON#42]
用cocoapods加载的HandyJSON（1.2.1），swift 3.0， xcode 8.0， iOS 9.0；在“模拟机”的iPhone5上会提示
Undefined symbols for architecture i386:的错误

**Comment by cijianzy** [comment]
您好，我这里没有任何问题的，请检查项目 Target->Build Settings->Other Linker Flags 是否链接了HandyJSON
![image](https://cloud.githubusercontent.com/assets/6985160/20296872/36fa5a20-ab48-11e6-9b19-f48ab856b1a3.png)

**Comment by yanjinquan** [comment]
谢了，刚刚解决了，是xcode的问题，我把自动生成的.frameWork文件删除就没问题了
