### ISSUE TITLE
继承之后，不走mapping方法

### ISSUE THREAD

**Issue by gdutxzy** [alibaba/HandyJSON#426]
class Human : NSObject ,HandyJSON{
    required override init() {
    }
}

class Female : Human  {
    var a : String?
    func mapping(mapper: HelpingMapper) {
        print(">>>>>>>>mapping")
    }
}

let model =  JSONDeserializer<Female>.deserializeFrom(dict: ["a":"2"])

代码如上，继承之后，子类不走mapping方法。HandyJSON (5.0.2)

**Comment by AlanFeiyang** [comment]
父类要先实现这个方法才可以
func mapping(mapper: HelpingMapper) {
print(">>>>>>>>mapping")
}
