### ISSUE TITLE
iOS 15 crash堆栈  _propertyDescriptionsAndStartPoint 请问handyjson还在维护么？

### ISSUE THREAD

**Issue by programer001** [alibaba/HandyJSON#438]
_propertyDescriptionsAndStartPoint (<compiler-generated>:0)
propertyDescriptions (Metadata.swift:214)
_transform (ExtendCustomModelType.swift:140)
_transform (ExtendCustomModelType.swift:135)
deserializeFrom (Deserializer.swift:78)
deserialize (Deserializer.swift:33)

**Comment by crazypoo** [comment]
pod command :find_and_replace("Pods/HandyJSON/Metadata.swift","if !(superclass is HandyJSON.Type) && !(superclass is HandyJSONEnum.Type) {", "if !(superclass is HandyJSON) && !(superclass is HandyJSONEnum) {")

**Comment by suyuexinok** [comment]
<img width="1908" alt="WeChatc56af87a84710590ed87cbefb24f6bde" src="https://user-images.githubusercontent.com/13246625/125743910-00b036a3-2c79-41e8-a665-b2ea137165e3.png">

**Comment by suyuexinok** [comment]
need help

**Comment by crazypoo** [comment]
@spicyShrimp #436

**Comment by lynnleelhl** [comment]
develop 分支已修复
https://github.com/alibaba/HandyJSON/tree/develop

**Comment by thisfin** [comment]
> develop 分支已修复
> https://github.com/alibaba/HandyJSON/tree/develop

子类继承, 父类的属性写不进去, 父类是UIViewController的子类, 是不是把NSObject排除的原因
JSONDeserializer.update(object: &vSelf, from: parameters)

**Comment by lynnleelhl** [comment]
> > develop 分支已修复
> > https://github.com/alibaba/HandyJSON/tree/develop
> 
> 子类继承, 父类的属性写不进去, 父类是UIViewController的子类, 是不是把NSObject排除的原因
> JSONDeserializer.update(object: &vSelf, from: parameters)

该问题已修复，查看最新 develop 分支
