### ISSUE TITLE
能否实现Int到String的自动转换

### ISSUE THREAD

**Issue by DonYang** [alibaba/HandyJSON#44]
有时候服务端下发的id可能是Int也可能是String
很多时候客户端其实不关心这个类型，只是用于展示数据
对于JSON中的Int数据，反序列化时接收者如果是String能否自动做转化

**Comment by xuyecan** [comment]
可以的，现在已经支持，如feature list中所述:
```
Type-Adaption, such as string json field maps to int property, int json field maps to string property.
```
Number到String，或者格式正确的String到Number，都是自动完成的。
