### ISSUE TITLE
ios15 crash

### ISSUE THREAD

**Issue by lazyid** [alibaba/HandyJSON#441]
![截屏2021-07-16 15 11 07](https://user-images.githubusercontent.com/3994089/125907272-d40321e0-a0c6-44b7-95fc-09e0daa90c21.png)

**Comment by lazyid** [comment]
已经使用了develop 还是不行

**Comment by xusion** [comment]
看不到图，是不是这行出问题了：
`
if !(superclass is HandyJSON.Type) && !(superclass is HandyJSONEnum.Type) {
                return nil
            }
`

Thread 1: EXC_BREAKPOINT (code=1, subcode=0x1864b5fd0)


iOS15 beta3

**Comment by THE13Hill** [comment]
Yes, like this

            if !(superclass is HandyJSON.Type) && !(superclass is HandyJSONEnum.Type) {
                return nil
            }
Thread 1: EXC_BREAKPOINT (code=1, subcode=0x18918efd0)

**Comment by lazyid** [comment]
> 看不到图，是不是这行出问题了：
> `if !(superclass is HandyJSON.Type) && !(superclass is HandyJSONEnum.Type) { return nil }`
> 
> Thread 1: EXC_BREAKPOINT (code=1, subcode=0x1864b5fd0)
> 
> iOS15 beta3



> 看不到图，是不是这行出问题了：
> `if !(superclass is HandyJSON.Type) && !(superclass is HandyJSONEnum.Type) { return nil }`
> 
> Thread 1: EXC_BREAKPOINT (code=1, subcode=0x1864b5fd0)
> 
> iOS15 beta3

![11111](https://user-images.githubusercontent.com/3994089/125925691-7422e762-64bf-42df-ae74-ad07bc0e301f.png)

现在可以吗?

Metadata 文件

146行

var superclass: Class? {

**Comment by lynnleelhl** [comment]
试一下最新的 develop

**Comment by lazyid** [comment]
> 试一下最新的 develop

最新的可以了 感谢
