### ISSUE TITLE
请问能否商用，1.8亿的用户

### ISSUE THREAD

**Issue by syyjay** [alibaba/HandyJSON#447]
看了这么多issues，每次升级新系统好像都不是很稳定，请问能否商用，1.8亿用户的app，后面用户还会增加

**Comment by RITL** [comment]
都1.8亿了, 就算是beta崩一下也挺爽的吧，这个体量的话建议换吧.. @syyjay

**Comment by kangbaobao** [comment]
不能用，每次系统升级真的会崩溃... 现在想换掉这个库也不知道怎么换掉只能凑合着用了

**Comment by paradiseduo** [comment]
用swift原生的吧

**Comment by xuyecan** [comment]
#466
