### ISSUE TITLE
对于JSON中某个String字段是一个JSON字符串有没有简便的转化方式

### ISSUE THREAD

**Issue by DonYang** [alibaba/HandyJSON#45]
在一些特殊的场景下，服务端下发的数据并不是严格按照JSON的格式的，比如JSON中某个String字段其实是一个JSON的字符串，在反序列化时我们势必要将其转化出来，有没有比较简便的方法

**Comment by xuyecan** [comment]
这里要细问一下，你是指，转换之后，Model中有一个String字段可能是一个JSON字符串？

**Comment by xuyecan** [comment]
如果是指 `Model中有一个String字段可能是一个JSON字符串`，那么，JSON中的JSON必然是被转义过的(否则就破坏JSON结构了)，如 `{"notJsonString":"value","jsonString":"{\"key\": \"value\"}"}`。那么，解析之后，Model中的`jsonString`字段会被赋值为`{\"key\": \"value\"}`，我感觉符合预期，没什么问题~
