### ISSUE TITLE
deserializeModelArrayFrom 为什么没有 designatedPath参数？

### ISSUE THREAD

**Issue by yansun2006** [alibaba/HandyJSON#48]
```Swift
public static func deserializeModelArrayFrom(json: String?) -> Array<T?>?
```
deserializeModelArrayFrom这个方法现在不能指定解析路径，对于这种情况如何处理？需要自己先定位JONS里面的数组？

**Comment by xuyecan** [comment]
这个方法是后来新加的，考虑适用面不广，就没支持那么完善。我这两天加一下，发个新版本。

**Comment by xuyecan** [comment]
fixed in [#758c92](https://github.com/alibaba/HandyJSON/commit/758c928828bfe5f0bef9611ea01fe9238317d494).
