### ISSUE TITLE
pod 只找到0.1.0版本

### ISSUE THREAD

**Issue by tjnuliyan** [alibaba/HandyJSON#49]
pod search :
-> HandyJSON (0.1.0)
   A Json Serialization & Deserialization Library for Swift
   pod 'HandyJSON', '~> 0.1.0'
   - Homepage: https://github.com/alibaba/handyjson
   - Source:   https://github.com/alibaba/HandyJSON.git
   - Versions: 0.1.0 [master repo]
(END)

**Comment by xuyecan** [comment]
是不是你本地pod很久没update过了。。尝试执行下 `pod repo update`，或者删掉pod的local仓库目录`~/.cocoapods/repos`然后重新`pod setup`。

**Comment by xuyecan** [comment]
更新下pod应该就能找到了~
