### ISSUE TITLE
iOS 18 报错 Function type mismatch, declared as '@convention(thin) (UnsafePointer<UInt8>, Int, Optional<UnsafeRawPointer>, Optional<UnsafeRawPointer>) -> Optional<@thick any Any.Type>' but used as '@convention(thin) (UnsafePointer<UInt8>, UInt, Optional<UnsafeRawPointer>, Optional<UnsafeRawPointer>) -> Optional<@thick any Any.Type>'

### ISSUE THREAD

**Issue by loveshort** [alibaba/HandyJSON#501]
Function type mismatch, declared as '@convention(thin) (UnsafePointer<UInt8>, Int, Optional<UnsafeRawPointer>, Optional<UnsafeRawPointer>) -> Optional<@thick any Any.Type>' but used as '@convention(thin) (UnsafePointer<UInt8>, UInt, Optional<UnsafeRawPointer>, Optional<UnsafeRawPointer>) -> Optional<@thick any Any.Type>'

**Comment by LengYi** [comment]
UInt 修改为Int即可

**Comment by iAmMccc** [comment]
官方已经不维护了，切换成原生的Codable方案吧。 可以考虑SmartCodable三方库。

**Comment by YourMir** [comment]
> 官方已经不维护了，切换成原生的Codable方案吧。 可以考虑SmartCodable三方库。

这个好用，我们公司已经迁移过来了，完美平替HandyJSON

**Comment by loveshort** [comment]
> UInt 修改为Int即可

是的，但是我并不打算使用handyJson

**Comment by ShawnMoo** [comment]
> 是的，但是我并不打算使用handyJson

是的，然后发现上次因为打包出错，使用的是特殊分支，直接改了
