### ISSUE TITLE
Xcode 16 compiler error.

### ISSUE THREAD

**Issue by ShawnMoo** [alibaba/HandyJSON#503]
When compiling the project using Xcode 16, a compilation error occurred with HandyJSON, and the issue was related to _getTypeByMangledNameInContext.

`let functionMap: [String: () -> Any.Type?] = [
                    "function": { _getTypeByMangledNameInContext(cMangledTypeName, UInt(getMangledTypeNameSize(cMangledTypeName)), genericContext: self.contextDescriptorPointer, genericArguments: self.genericArgumentVector) }
                ]
`
error message:

Function type mismatch, declared as '@convention(thin) (UnsafePointer<UInt8>, Int, Optional<UnsafeRawPointer
Optional<UnsafeRawPointer>) -> Optional<@thick any Any.Type>' but used as '@convention(thin) (UnsafePointer<Unt8>, UInt,
Optional<UnsafeRawPointer>, OptionakUnsafeRawPointer>) - Optional@thick any Any.Type>'

**Comment by ShawnMoo** [comment]
This error occurs when a special branch is used

**Comment by RajaveluC** [comment]
Hi @ShawnMoo How did you manage to solve this issue?
