### ISSUE TITLE
sub class object missed during deserialization

### ISSUE THREAD

**Issue by pennsong** [alibaba/HandyJSON#53]
prettify json string:  {
  "_id" : "582d633ef1a0b90950782205",
  "authorId" : {
    "nickname" : "p1别名",
    "_id" : "582c549d0bd653ad5fb04336",
    "username" : "p1",
    "avatar" : "remote_default_user.png"
  },
  "commentIds" : [

  ],
  "placeName" : "上海",
  "content" : "testContent2",
  "createdTime" : 1234567891,
  "tag" : "art",
  "relatedUserIds" : [

  ],
  "image" : "1478704739.71422",
  "loc" : [
    121.456748,
    31.262244
  ],
  "read" : 0
}

after deserialization
authorId: nil
commentIds: nil
relatedUserIds: nil

how can i get the above three field back?

Thanks in advance!

**Comment by pennsong** [comment]
sorry, my mistake, I used "AnyObject" for authorId, commentIds, relatedUserIds
so it's not a bug

**Comment by xuyecan** [comment]
`HandyJSON` can not infer enough type-information to resolve the property from `AnyObject`, such as `init function`, `memory size`, etc. That's why It got nil. ：）
