### ISSUE TITLE
JSONSerializer能否支持mapping？

### ISSUE THREAD

**Issue by mrdaios** [alibaba/HandyJSON#56]
看到alibaba又出了一款json序列化的框架
* HandyJSON
* fastjson

全国人民发来贺电，表示非常感谢.

**Comment by xuyecan** [comment]
嗯，这个应该要加的，正在考虑怎么加入这个功能。现在接口上再加东西可能风格不太好，考虑升个大版本一起调整下。

**Comment by mrdaios** [comment]
@xuyecan  很期待哦。之前OC版本用的YYModel。现在正准备找swift版本的。
