### ISSUE TITLE
Each property should be handyjson-property type

### ISSUE THREAD

**Issue by MysteryRan** [alibaba/HandyJSON#59]
如果我定义的属性 是自己开发需要 不需要字典转模型的属性 该怎么区分呢

**Comment by yansun2006** [comment]
我这边也遇到类似问题，就是我的一个模型里面有一些属性，这个属性的类型不是JSON里面的基本类型，
但是这个属性不需要JSON转模型，自己编程需要而已，如下：
`var imageSize = CGSize.zero  //图片尺寸`

这时运行会崩溃 “Each property should be handyjson-property type”，
如果设置为可选类型就没有问题,但是现在编程需要把它设置为一个非可选型，以便提供Objective-C代码调用（OC代码导入Swift的代码时，对于非Class类型的可选型如Int?,Float?,CGSize?等是导入不了的）
`var imageSize: CGSize?`

希望能做到对于不需要转模型的字段，不去约束这些字段的类型

**Comment by xuyecan** [comment]
很有价值的建议。我这两天高优先级解决一下。

**Comment by xuyecan** [comment]
已经发布1.4.0版本进行支持。参考文档：https://github.com/alibaba/HandyJSON/blob/master/README_cn.md#%E6%8E%92%E9%99%A4%E6%8C%87%E5%AE%9A%E5%B1%9E%E6%80%A7 。

**Comment by yansun2006** [comment]
非常感谢如此快速的跟进

**Comment by MysteryRan** [comment]
非常感谢
