### ISSUE TITLE
Swift3.0 如何使用T 定义我要声明的Data

### ISSUE THREAD

**Issue by shiqianren** [alibaba/HandyJSON#61]
Optional<T>/ImplicitUnwrappedOptional<T> // T is one of the above types

**Comment by xuyecan** [comment]
能具体描述一下场景吗？文档里T只是一个指代，指代已经支持`HandyJSON`的类型。

**Comment by shiqianren** [comment]
我想封装一个base 里面包含(code,msg,data),data是任意类型的，我继承了handyJson，请问怎么处理这个data

**Comment by xuyecan** [comment]
如果你是指需要支持泛型的话，你可以这么声明：

```
class Base<T: HandyJSON> {
    var code: Int?
    var msg: String?
    var data: T?
}
```

这样的话，你在实例化`Base`时，需要指明这个`T`的具体类型，这个类型必须是实现了`HandyJSON`协议的。

**Comment by xuyecan** [comment]
如果`data`字段需要到运行时才知道是什么类型，那只能够用`specify`函数来自定义解析了。
参考：https://github.com/alibaba/HandyJSON/blob/master/README_cn.md#%E8%87%AA%E5%AE%9A%E4%B9%89%E8%A7%A3%E6%9E%90%E8%A7%84%E5%88%99

**Comment by shiqianren** [comment]
class Base<T: HandyJSON> {
    var code: Int?
    var msg: String?
    var data: T?
}
这个时候好像不能用JSONDeserializer<Base>.deserializeFrom（）处理了data数据了
我是想用这个base去接受服务器传过来的数据，
再在对应的Model层次去处理这个data

**Comment by xuyecan** [comment]
不好意思今天才看到这条信息。。我测试是没问题的。参考：

```swift
class BaseResponse<T: HandyJSON>: HandyJSON {
    var code: Int?
    var data: T?

    required init() {}
}

class Sample: HandyJSON {
    var id: Int?

    required init() {}
}

let sample = Sample()
sample.id = 2
let resp = BaseResponse<Sample>()
resp.code = 200
resp.data = sample

let jsonString = resp.toJSONString()!

print(jsonString)
if let mappedObject = JSONDeserializer<BaseResponse<Sample>>.deserializeFrom(json: jsonString) {
    print(mappedObject.data?.id)
}
```

**Comment by AndSync** [comment]
就是这个T必须明确是吗？不能写成JSONDeserializer<BaseResponse<T>>.deserializeFrom(json: jsonString) 或者BaseResponse<T>.deserializeFrom(json: jsonString) ？？？
