### ISSUE TITLE
mapper.specify(property: &T, name: "String"), name 参数能否支持路径解析

### ISSUE THREAD

**Issue by Alchemistxxd** [alibaba/HandyJSON#62]
例如 mapper.specify(property: &userName, name: "user.name")

**Comment by xuyecan** [comment]
目前还不支持，只能调用如`JSONDeserializer<T>.deserializeFrom(json: jsonString, designatedPath: "**.**.user")`，指定整个model从哪个路径开始解析。

`specify`目前只能指定以哪个key解析该字段。
