### ISSUE TITLE
mapper.specify用法请教

### ISSUE THREAD

**Issue by tonggang2013** [alibaba/HandyJSON#63]
```
class Knowledge : HandyJSON{
    var title: String?
    var desc: String?
    var exercises:[Exercise]?
    required init() {}
    
    func mapping(mapper: HelpingMapper) {
        // 指定 JSON中的`tests`字段映射到Model中的`exercises`字段
        mapper.specify(property: &exercises, name: "tests")
    }
}

```
在实际使用过程中，json字符串中的tests并没有映射到exercises，是我的用法不对么？

**Comment by tonggang2013** [comment]
如果我在Knowledge中增加var tests:[Exercise]? 这个变量，那么json中的tests会被映射到Knowledge中的tests中。

**Comment by xuyecan** [comment]
收到，稍迟些我验证下再答复你。

**Comment by xuyecan** [comment]
我测试没能复现，在 5s iOS9上，swift 3.0环境。
代码见：https://gist.github.com/xuyecan/f33d4e74367a31ffff5bc0fc238a07e7

希望能提供下复现代码~

**Comment by tonggang2013** [comment]
sorry, 忘了说，我是用在mac上，10.11.5， xcode 8.1, swift 3.0环境.

**Comment by tonggang2013** [comment]
如果我用 deserializeFrom(dict: ...)，那mapping会起作用么？

**Comment by xuyecan** [comment]
是的，`mapping`方法是定义来Model的类定义里，所以，无论用哪个函数反序列化得到这个对象，`mapping`都起作用。
