### ISSUE TITLE
How to specify mapper for serialization?

### ISSUE THREAD

**Issue by francescortiz** [alibaba/HandyJSON#64]
When I try to serialize a Date and some custom fields. Serializing a Date crashes, and I don't see how to provide a serialization mapper. Am I missing something or is it a missing feature?

**Comment by xuyecan** [comment]
Sorry that serialization is not so well supported by the current release version. The mapper is only working on deserialization. Mapper for serialization is on my TODO list, I'm working on it now.

**Comment by francescortiz** [comment]
Thank you for you answer. I made a quick implementation but my swift knowledge is not deep enough to make something as nice as your code. If you want, I can make a pull request, but you will have to give me feedback on how to improve my code.

**Comment by xuyecan** [comment]
What bother me now is how to reuse the mapper designed for deserialization on serialization. Or at least keep the same API style. Better let me work out an API definition first, maybe today.
If you are confident your implementation has solved this headache, make your pull request and I'll appreciate that.

**Comment by xuyecan** [comment]
1.5.0 has been released. Now you can specify a mapper for serialization. See the README.

**Comment by francescortiz** [comment]
Woe, thank you!

**Comment by xuyecan** [comment]
After release 1.5.0 I fix 2 issues...And now the version is 1.5.2. ：）

**Comment by francescortiz** [comment]
Great thank you!

**Comment by francescortiz** [comment]
It works like charm. I also found an undocumented DateFormatterTransform in the source code. Thank you!
