### ISSUE TITLE
如果我的model里有一个 var data: Any? any类型的可选属性，转换一直为nil

### ISSUE THREAD

**Issue by ac1217** [alibaba/HandyJSON#66]
转换的值有可能是Array或者Dictionry类型，请问怎么声明类型能成功转换呢？

**Comment by ac1217** [comment]
我希望是这样：它原来是什么类型就直接赋值，不需要做处理

**Comment by xuyecan** [comment]
本周发布新版本，新版本中将提供支持方式。

**Comment by xuyecan** [comment]
新版本已经发布，1.5.0，请更新后尝试。有任何问题或者建议，可以继续在这里讨论~

**Comment by ac1217** [comment]
谢谢大神

**Comment by angelen10** [comment]
@ac1217 @xuyecan 请问一下你这个模型怎么声明，我也遇到这个问题，不知道怎么声明，有空烦请帮忙看看 https://github.com/alibaba/HandyJSON/issues/200
