### ISSUE TITLE
Problem when serializing to simple Dictionnary with Enum

### ISSUE THREAD

**Issue by fencingCode** [alibaba/HandyJSON#67]
Hello,
when sending my serialized object in my URLRequest with Alamofire,
my REST API didn't worked and the log said : "NSInvalidArgumentException [blah blah] JSON(write)".
I have used the toSimpleDictionary() func to send my json object.
I figured out that my object contained an enum and that when it is serialized the enum
is transforming into "MyModule.MyEnum.Value" instead of "Value".
To illustrate this clearly, see the class

```swift
class MyObject: HandyJSON {
 var someInfo: String?
 var myEnum: MyEnum?

 required init() {}
}
```

see the enum
```swift
enum MyEnum: HandyJSONEnum {
 case MyValue
 case MyOtherValue

 static func makeInitWrapper() -> InitWrapperProtocol? {
        return InitWrapper<String>(rawInit: MyEnum.init)
 }
}
```

see example of use
```swift
let myObject = MyObject()
request.someInfos = "some useful infos"
request.myEnum = MyEnum.MyValue
var urlRequest = URLRequest(url: "myURL")
urlRequest = try JSONEncoding.default.encode(urlRequest, with: myObject.toSimpleDictionary())
Alamofire.request(urlRequest)
```
My solution is to modify JSONSerializer.swift
```swift
extension GenericObjectTransformer {
 static func transformToSimpleObject(object: Any) -> Any? {
 // ...
 case enum:
  return String(describing: object) as Any
 // ...
 }
}
```
i'm aware that in this case, the result of your func will not be a pure "object"
but it will match my REST API regardless of the module name or enum name,
just the value is needed (a string in my case, i didn't try an int or something else).
What do you think ?

**Comment by xuyecan** [comment]
The time I designed the original serialization method I try to accomplish that every object can serialize to string naturally, which means no protocol has to conform to, no transformer has to implement, etc.

But now it proof that no constraint lead to much restriction especially when dealing with Enum and Customization. So I refactor the implementation, and make use of the transformer in [ObjectMapper](https://github.com/Hearst-DD/ObjectMapper).

**Comment by xuyecan** [comment]
The 1.5.0 version has been released. Serialization is well supported now. See the README and the codes. Any question or advice, let me know. :)

**Comment by fencingCode** [comment]
Ok thank you for your time and shares,
i will have some other questions because
i had problem while receiving html content in a deserialized property
but i will put this story in another issue soon if 1.5.2 is not resolving it ;-)
