### ISSUE TITLE
手动导入HandyJSON后，总会提示 you don't have permission to view it

### ISSUE THREAD

**Issue by aksskas** [alibaba/HandyJSON#71]

**Comment by xuyecan** [comment]
貌似是一个常见问题，参考 http://www.jianshu.com/p/b4b54c43b4d0 这个哥们的解法试下呢？

**Comment by aksskas** [comment]
在这之前我已经将这些方法都试过了，但都没有解决，还是很感谢你的回复！

**Comment by xuyecan** [comment]
嗯，你现在是编出framework导入还是源码拖进去的呢？

**Comment by xuyecan** [comment]
可以两种都试下。demo没问题的话，那估计就是哪里环境配置的问题。

**Comment by aksskas** [comment]
嗯，好，谢谢了
