### ISSUE TITLE
当类型中存在Date类型的字段时, 序列化失败

### ISSUE THREAD

**Issue by ZhangZihe** [alibaba/HandyJSON#74]
当类型中存在Date类型的字段时, 序列化失败
并且当json字符串中含有Date类型的字段时, 反序列化为对象后, 对象内的Date类型也是nil
请查看一下代码:
```
import UIKit
import HandyJSON


class Temp: HandyJSON {
    var name:String?
    var date:Date?
    required init(){
        name = "df"
        date = Date.init(timeIntervalSinceNow: 0)
    }
}

let json = Temp().toJSONString()
let r = JSONDeserializer<Temp>.deserializeFrom(json: json)
print(json)
print(r?.name)
print(r?.date)
```

**Comment by ZhangZihe** [comment]
json为nil

**Comment by xuyecan** [comment]
Date没有默认实现HandyJSON的类型，需要构造一个transformer指定解析，或者选择一个sdk提供的默认Transformer。如：

```swift
struct DateSample: HandyJSON {

    var aInt: Int?
    var date: Date?

    mutating func mapping(mapper: HelpingMapper) {
        mapper <<<
            self.date <-- DateTransform()
    }
}

let json = "{\"aInt\": \"2\", \"date\": 1484196879}"
let model = JSONDeserializer<DateSample>.deserializeFrom(json: json)!
print(model.date!)  // print: 2017-01-12 04:54:39 +0000
print(model.toJSON()!) // print: ["aInt": 2, "date": Optional(1484196879.0)]
```

HandyJSON还提供了以下的Date相关的Transformer：
* DateTransform
* DateFormatterTransform
* ISO8601DateTransform
* CustomDateFormatTransform

**Comment by ZhangZihe** [comment]
@xuyecan  如果能有一个全局的方式, 可以设置默认的时间解析方法, 那必是极好的

**Comment by banxi1988** [comment]
@ZhangZihe 可以的.你在你自己的项目中,扩展 Date 使它实现 HandyJSONCustomTransformable 协议即可.
`extension Date: HandyJSONCustomTransformable`
然后你自己实现从 `NSObject` 到 Date 的转换.

比如测试代码中,有实现 URL 默认解析方式的示例测试代码.

https://github.com/alibaba/HandyJSON/blob/master/HandyJSONTests/CustomJSONTransformableTypeTest.swift

**Comment by ZhangZihe** [comment]
@banxi1988 貌似HandyJSONCustomTransformable 并不在已发布的1.5.2版本之中

**Comment by banxi1988** [comment]
@ZhangZihe 你可以直接在 Podfile 中配置 HandyJSON 指向 master
