### ISSUE TITLE
Array<Object> 这样得出来的json 是使用不了的 都变成了[Any?,...] 了...类型丢了.但是打印出来的json是正常的

### ISSUE THREAD

**Issue by longlylong** [alibaba/HandyJSON#76]
Array<Object> 这样得出来的json 是使用不了的 都变成了[Any?,...] 了...类型丢了.但是打印出来的json是正常的

**Comment by banxi1988** [comment]
@longlylong 给个例子看看. 不太理解你说的.

**Comment by longlylong** [comment]
class A :HandJson{
var p  = Array<P>()
}
class P:HandJson{
var  name = "dddd"
}
A().toJSON()
这个的结果就是{"A":{p:[Any?],[Any?],...}}
正确应该是{"A":{p:["name":"dddd"],["name":"dddd"],...}}

**Comment by banxi1988** [comment]
@longlylong  我在我的一个 PR 中修复了些问题.
https://github.com/alibaba/HandyJSON/pull/77
你可以试试我的这个分支.

**Comment by xuyecan** [comment]
我认真考虑了这个问题，觉得这是理论上的限制，没有办法做出改进的。

`toJSON()` 接口返回的是一个字典，字典中各个值，是运行时通过反射的方式解析 `A` 类得到的，也就是，需要到运行时，才可能检测到各个值的类型。而你这里说的类型是编译期的概念。打个比方，如果你能知道 `let a = A().toJSON()` 得到的 `a` 是 `[String: [[String: String]]` 类型，意味着你可以写代码的时候，IDE就可以给你补全 `a["p"].count` 后边的 `.count`(有类型信息)。但这个 `a` 是运行时才知道的，不可能编译期就获得它的类型。

也就是说，`toJSON()` 返回的字典，每个值的类型都是和 `A` 类对应的，但你只能通过强转的形式，让它成为对应的类型(因为你可以根据对应关系明白每个转换出来的值会是什么类型)。如:

```
if let p = A().toJSON()?["p"] as? [Any?] {
    if let first = p.first as? String {
        print(first)
    }
}
```
