### ISSUE TITLE
Would it be possible to not have objects inherit from HandyJSON?

### ISSUE THREAD

**Issue by FruitAndAShape** [alibaba/HandyJSON#79]
So instead, one could do something like this...

`let json = HandyJSON.toJSONString(myObject)!`

**Comment by banxi1988** [comment]
@FruitAndAShape In theory, it's possible. While HandyJSON is a simple protocol. you don't need to inherit from it. just declare it conform to it. like `extension MyObject:HandyJSON` .so you see it's simple and clear.

**Comment by xuyecan** [comment]
Like @banxi1988 said, it's possible. Actually, at the first version, you do not need the model definition conform to HandyJSON for serializing. But soon afterwards I found that without a protocol I can't support any customizing for any field. But this feature is important according to many user's requests.

After all, the HandyJSON protocol is simple. Most time your extra work is just need to declare an empty `init` method.
