### ISSUE TITLE
Case insensitive deserialisation

### ISSUE THREAD

**Issue by FruitAndAShape** [alibaba/HandyJSON#80]
Is it possible to automatically do case-insensitive deserialisation?

**Comment by banxi1988** [comment]
@FruitAndAShape that's interesting idea.  I'll do some exp in my folk.

**Comment by xuyecan** [comment]
Yes, I put an option in the 1.5.2 version. Before you do any deserialization by HandyJSON, call this:

```
HandyJSONConfiguration.deserializeOptions = .caseInsensitive
```

After that, all the deserialization dealing with the field keys is case-insensitive.
