### ISSUE TITLE
手动安装失败

### ISSUE THREAD

**Issue by TonyReet** [alibaba/HandyJSON#83]
使用cocopods可以安装，但是手动安装失败，提示Use of unresolved identifier 'JSONSerialization'等错误，请问手动安装可以更简单点吗，感觉有点麻烦，谢谢

现在使用carthage安装成功了，谢谢了哈

**Comment by banxi1988** [comment]
这个问题,是因为 Serializer.swift 文件中引用到了 JSONSerialization 这个类. 所以有可能提示编译错误.
我提了一个 PR ,增加了 `import Foundation` 导入的声明.
见 https://github.com/alibaba/HandyJSON/pull/84

**Comment by xuyecan** [comment]
#84 merged.

感谢 @banxi1988 ！

**Comment by TonyReet** [comment]
好的，谢谢

2017-02-10 15:27 GMT+08:00 banxi <notifications@github.com>:
