### ISSUE TITLE
序列化不支持嵌套对象

### ISSUE THREAD

**Issue by GTMYang** [alibaba/HandyJSON#92]
序列化是否支持嵌套对象？怎么处理？

**Comment by banxi1988** [comment]
@GTMYang 嵌套是支持的. 正常写就可以了.

参考代码见测试用例:
https://github.com/alibaba/HandyJSON/blob/master/HandyJSONTests/NestObjectTest.swift

如果你遇到问题的话, 可以提供下测试用例.
