### ISSUE TITLE
含有特殊字符的数据序列化后不能再反序列化！

### ISSUE THREAD

**Issue by GTMYang** [alibaba/HandyJSON#93]
含有特殊字符比如 \“， 这样的字段序列化之后再反序列化就失败，\ 丢失了

**Comment by GTMYang** [comment]
求怎么破！！！

**Comment by banxi1988** [comment]
@GTMYang Hi, 我测试没有问题. 请检查下你的 JSON 格式是否正确? 如果确实有问题.
请提供下 JSON. 因为按理论上应该没这个问题. 目前的版本,实现上是直接用 Foundation 的 JSONSerialization 解析 string的.

**Comment by GTMYang** [comment]
原始json串：
{
    "Colors": [
        "Gold",
        "Silver"
    ],
    "AllSizes": [
        "84\" Panel",
        "95\" Panel"
    ],
    "AllColors": [
        "Gold",
        "Silver"
    ],
    "SalesPrice": 20.16,
    "IsAvailable": true,
    "ProductColors": [
        {
            "PrimaryColor": "Gold",
            "ItemNo": "II40-575",
            "PicPath": "http://192.168.20.44/Files/Olliix/2016/07/04/ab9bd939-c6ac-4678-b60d-2fca4e43a108/II_Ory_WP_gold_front.jpg"
        },
        {
            "PrimaryColor": "Silver",
            "ItemNo": "II40-573",
            "PicPath": "http://192.168.20.44/Files/Olliix/2016/07/04/957b09b5-92c0-46c3-a22d-9193e139c157/II_Ory_WP_silver.jpg"
        }
    ],
    "ShowColorStyle": null,
    "IsSample": false,
    "MinPrice": 0,
    "MaxPrice": 0,
    "Product_ID": "5416",
    "RelatedItems": [],
    "Categories": [
        {
            "ID": 12,
            "Division_ID": "PET",
            "Name": "Panel",
            "DivisionName": null
        }
    ],
    "RetailCategories": [
        {
            "ID": 47,
            "Division_ID": null,
            "Name": "Curtains",
            "ParentID": 3,
            "Sort": 0,
            "RootID": 0,
            "CreatedOnUtc": "2016-06-28T08:19:50.013",
            "QueryExpansion": "TopTreatment,Size",
            "Clickable": true,
            "Children": false,
            "FullName": null,
            "IsMapping": false,
            "NowLevel": 0,
            "AllLevel": 0,
            "Childrens": null,
            "CombineCategoryForSearch": null
        }
    ],
    "EECRetailCategories": [],
    "Families": [],
    "RoomTypes": [],
    "LifeStyles": [],
    "Division": null,
    "RetailDivisionRelation": [],
    "Brand": null,
    "RetailItemIDArray": null,
    "PrimaryPic": null,
    "Qty": 0,
    "ID": "05e4b6c3-69b2-44ac-ba5e-eb4129242aff",
    "Picture_ID": "ab9bd939-c6ac-4678-b60d-2fca4e43a108",
    "ItemNo": "II40-575",
    "UPC": "675716716370",
    "SetIncludes": "1 Window Curtain,",
    "SizeName": "84\" Panel",
    "SizeDescription": "50x84\",",
    "CareInstructions": "MACHINE WASH COLD, GENTLE CYCLE, AND SEPERATELY. DO NOT BLEACH. TUMBLE DRY LOW. REMOVE PROMPTLY. DO NOT IRON. IF THERE IS NO FREE MOVEMENT IN THE WASHER OR DRYER, USE LARGE CAPCACITY COMERCIAL WASHER/DRYER.",
    "Division_ID": "WIN",
    "ProductName": "Ory Metallic Ikat Printed Window Curtain",
    "Description": "Add subtle metallic for a little luster,  our Ory window panel is the perfect update of urban glitz. Printed gold metallic ikat adds a little sparkle for a modern touch, while the textured fabric and natural color softens the panel for an urban look. Grommet top detail makes it easier to hang, open, and close panels throughout the day. Fits up to 1.25\" diameter rod.",
    "PrimaryColor": "Gold",
    "SecondaryColor": null,
    "OtherColor": null,
    "RetailBrandName": "INK+IVY",
    "RetailName": "Ory",
    "BriefDesc": "Metallic Ikat Printed Window Curtain",
    "CustomerCode": "OLLIIX",
    "PatternTypeName": "Print",
    "Material": "90% Polyester 5% Linen 5% Cotton",
    "MaterialAttrName": "Polyester/Linen/Cotton",
    "PicPath": "http://192.168.20.44/Files/Olliix/2016/07/04/ab9bd939-c6ac-4678-b60d-2fca4e43a108/II_Ory_WP_gold_front.jpg",
    "Site_ID": 3,
    "RetailItemNo": 111483,
    "PackQty": 4,
    "QtyPerCarton": 4,
    "MinOrderQty": 4,
    "InvQty": 11,
    "IsSpecial": false,
    "IsNew": false,
    "RetailPrice": 20.16,
    "MinAdvicePrice": null,
    "Weight": 9.471365,
    "Width": 10.2362,
    "Length": 12.2047,
    "Height": 10.6299,
    "ExpectedInStockDate": null,
    "NewIntroEndDate": "2016-12-18T00:00:00",
    "CreatedOnUtc": "2016-07-04T02:06:43.177",
    "UpdatedOnUtc": "2017-01-06T10:56:21.51",
    "Picture": null,
    "ActionType": 0,
    "IsFinalOne": false,
    "DiscontinueDate": null,
    "RetailItemComponents": [],
    "AdditionalPictures": null,
    "ItemStatus": 1,
    "Status": 1,
    "DivisionName": null,
    "CategoryName": null,
    "TopTreatment": "Grommets",
    "FillType": "",
    "MetalFinish": null,
    "Shape": "",
    "TopperType": "",
    "ThreadCount": 0,
    "RoomType": null,
    "LifeStyle": null,
    "InitialInventoryAvailableDate": "2016-07-03T18:08:48.863",
    "RetailCategoryID": 0,
    "RetailCategoryIDs": null,
    "RetailItemInvLocRelation": [
        {
            "RetailItem_ID": "05e4b6c3-69b2-44ac-ba5e-eb4129242aff",
            "Location_ID": "LDC",
            "InvQty": 11,
            "IncomingInvQty": 0,
            "IncomingInvDate": null,
            "InvLocation": {
                "ID": "LDC",
                "Name": "Livermore",
                "Country_ID": "US",
                "StateProvince_ID": "CA",
                "Description": "Livermore Drop Ship",
                "StateProvince": {
                    "ID": "CA",
                    "Country_ID": "US",
                    "Name": "California",
                    "TaxRate": 0.095,
                    "IsResaleCertificateNoRequired": true,
                    "Country": {
                        "ID": "US",
                        "Name": "United States"
                    }
                },
                "RetailItemInvLocRelation": null,
                "OlliixOrderItemInvLocQtyRelation": null,
                "LineNo": 0
            },
            "willUsedQty": 0,
            "IsNotifyMe": false,
            "strIncomingInvDate": null,
            "TempSortNum": 0
        }
    ],
    "WareHouseTotalQty": null,
    "IncomingInvTotalQty": null
}

**Comment by GTMYang** [comment]
对象结构如下：

```swift
import HandyJSON

class Product: HandyJSON {
    
    var IsSample: Bool!
    // MARK: - Detail
    var AllColors:[String]!
    var Colors:[String]!
    var AllSizes:[String]!
    var ItemNo: String!
    var PicPath: String!
    var PrimaryColor: String!
    var ProductName: String!
    var Product_ID: String!
    var RetailBrandName: String! /// by
    var RetailItemInvLocRelation: [ItemInvLoc]!
    var RetailPrice: Double!
    var SalesPrice: Double!
    var UPC: String!
    
    // MARK: - Description
    var CareInstructions: String!
    var Description: String!
    var Height: Float!
    var Length: Float!
    var Width: Float!
    var Material: String!       /// material detail
    var SetIncludes: String!        /// detail
    var SizeDescription: String! {   /// detail 
        get {
            return self.SizeDescription.replacingOccurrences(of: "\"", with: "\\\"")
        }
    }
    
    var SizeName: String!           /// detail
    
    // MARK: - 本地存储增加的字段
    var PrimarySize: String? // 选中的size
  
    var Qty: Int = 0  // 购买数量
    var checked: Bool = true
    var OldItemNo: String?

    
    required init() {}
}

class ItemInvLoc: HandyJSON {
    var IncomingInvDate: String?
    var InvLocation: Location!
    var InvQty: Int!
    
    required init() {}

}


class Location: HandyJSON {
    var Name: String!  /// Loc
    var StateProvince: Province!
    
    required init() {}

}

class Province: HandyJSON {
    var Country_ID: String!
    var ID: String!
    
    required init() {}
 
}
```

**Comment by GTMYang** [comment]
第一步： 反序列化成对象， 没问题。
第二步：我将对象序列化成json串，嵌套对象不能序列化。我用下面的方法处理了下

```swift
class ItemInvLoc: HandyJSON, CustomStringConvertible {
    var IncomingInvDate: String?
    var InvLocation: Location!
    var InvQty: Int!
    
    required init() {}
    
    var description: String {
        get {
            return JSONSerializer.serialize(model: self).toJSON()!
        }
    }
}


class Location: HandyJSON, CustomStringConvertible {
    var Name: String!  /// Loc
    var StateProvince: Province!
    
    required init() {}
    
    var description: String {
        get {
            return JSONSerializer.serialize(model: self).toJSON()!
        }
    }
}

class Province: HandyJSON, CustomStringConvertible {
    var Country_ID: String!
    var ID: String!
    
    required init() {}
    
    var description: String {
        get {
            return JSONSerializer.serialize(model: self).toJSON()!
        }
    }
}

```

然后将序列化出来的串处理一下：

```swift
jsonString.replacingOccurrences(of: "\"{", with: "{")
                .replacingOccurrences(of: "}\"", with: "}")
                .replacingOccurrences(of: "\"[", with: "[")
                .replacingOccurrences(of: "]\"", with: "]")
                .replacingOccurrences(of: "\n", with: " ")
                .replacingOccurrences(of: "\t", with: " ")
                .replacingOccurrences(of: "\r", with: " ")

```

**Comment by banxi1988** [comment]
@GTMYang 你的原始 json 字符串格式是错误的. 而且多个地方是错误的.
主要是双引号不匹配, 没有转义.
第一个地方在:

```
"AllSizes": [
"84" Panel",
"95" Panel"
],
```

中间部分也有:
![image](https://cloud.githubusercontent.com/assets/726774/23295514/fe6f3ece-faab-11e6-837b-7e8f0b0fdca3.png)

你也可以通过在线格式化工具,先验证下格式是否正确.
http://tool.oschina.net/codeformat/json

**Comment by GTMYang** [comment]
@banxi1988 好的，多谢了！
