### ISSUE TITLE
望新增接口支持

### ISSUE THREAD

**Issue by a5978445** [alibaba/HandyJSON#96]
在我看来一个完整的序列化接口应该是这样：
 deserialize:支持json -> model, jsonString -> model,
         jsonData -> model,dictionary -> model
 serialization:支持model -> json, model -> jsonString,
         model -> jsonData, model -> dictionary
尤其是 model -> data 的互转这个用的非常多

看了大神的接口却并没有完整支持支持，虽然用户在你的基础下修改一下也并不麻烦，但是我还是希望您能完善一下。
对于： func deserialize(from dict: NSDictionary?, designatedPath: String? = nil) -> Self? 
这个接口我想问下，为什么没有使用Dictionary 作为传入参数，而采用NSDictionary

**Comment by banxi1988** [comment]
@a5978445 想法很不错, 我觉得你可以提一个 PR 上来. 也应该是极好的.

**Comment by xuyecan** [comment]
@a5978445 已在PR回复，请review~
