### ISSUE TITLE
请教下大神，我序列化的时候怎么排除某些字段

### ISSUE THREAD

**Issue by ac1217** [alibaba/HandyJSON#98]
因为有2个字段是UIImage类型
但是我实现了
func mapping(mapper: HelpingMapper) {
        mapper >>> self.image
        mapper >>> self.thumbnailImage
    }
这个函数没效果，序列化也会失败，请教下我该怎么写

**Comment by xuyecan** [comment]
麻烦把完整的类结构定义贴一下，和具体的JSON字符串，我这边尝试复现一下。

**Comment by ac1217** [comment]
import UIKit
import HandyJSON

let kChatImageMessageCellImageMaxW: CGFloat = 150

class ChatImageMessage: ChatInfoMessage {
    
    required init() {
        super.init()
    }
    
    func mapping(mapper: HelpingMapper) {
        mapper >>> self.image
        mapper >>> self.thumbnailImage
    }
    
    var imageUrl: String?
    var imageWidth: CGFloat = kChatImageMessageCellImageMaxW
    var imageHeight: CGFloat = kChatImageMessageCellImageMaxW
    
    var image: UIImage? {
        didSet {
            thumbnailImage = image?.scaleImage(width: kChatImageMessageCellImageMaxW)
        }
    }
    var thumbnailImage: UIImage?
}
这个类是继承父类的，都遵循了HandyJSON协议，序列化TextMessage是没问题的，但是ImageMessage就会失败，是因为存在有UIImage属性，如果把那两个UIImage的属性注释了就没问题

**Comment by ac1217** [comment]
对了，再问下，反序列化的时候是不是不会触发didSet监听器呢？

**Comment by banxi1988** [comment]
@ac1217  对于序列化 UIImage 属性的支持多的话,可以尝试让 `UIImage` 实现 `HandyJSONCustomTransformable` 协议试试.
虽然我没有试过, 但是感觉应该不会触发 didSet , 你可以试试.
因为 HandyJSON 是直接写内存的.

**Comment by xuyecan** [comment]
1. 我测试如下代码，貌似没有问题：
```
class ChatInfoMessage: HandyJSON {
    var aInt: Int?

    required init() {}
}

let kChatImageMessageCellImageMaxW: CGFloat = 150

class ChatImageMessage: ChatInfoMessage {

    required init() {
        super.init()
    }

    func mapping(mapper: HelpingMapper) {
        mapper >>> self.image
    }

    var imageUrl: String?

    var image: UIImage? {
        didSet {
            print("hello")
        }
    }
}

let jsonString = "{\"aInt\": 12, \"image\": \"fake\", \"imageUrl\": \"http://image.test\"}"
if let model = ChatImageMessage.deserialize(from: jsonString) {
    print(model.aInt)
    print(model.imageUrl)
}

// output:

Optional(12)
Optional("http://image.test")
```
2. 确实不会触发，如 @banxi1988 所说，HandyJSON是直接写内存赋值的。这倒是个隐患，我先在文档声明一下，后续看看怎么弄。

**Comment by xuyecan** [comment]
我又换几种情况试了一下，貌似遇到了些问题。上面那个1不作为结论，稍等我研究一下。

**Comment by ac1217** [comment]
extension UIImage: HandyJSONCustomTransformable {
    /// 返回可供 `JSONSerialization` 序列化的对象
    public func toJSONValue() -> Any? {
        
        let imgData = UIImageJPEGRepresentation(self, 1)

        return imgData?.base64EncodedString()
    }

    
    
    
    /// 将 `JSONSerialization` 反序列化生成的 `NSObject` 转换到对应 Model 对象.
//    public static func transform(from object: NSObject) -> Self? {
//        
//        if let str = object as? String, let data = Data(base64Encoded: str) {
//            
//            return UIImage(data: data)
//            
//        }
//        return nil
//        
//    }
    
    /// 返回可供 `JSONSerialization` 序列化的对象
//    public func toJSONValue() -> Any? {
//        
//        let imgData = UIImageJPEGRepresentation(self, 1)
//        
//        return imgData?.base64EncodedString()
//        
//    }
}
是这样实现协议方法吗？
编译报这个错
method 'transform(from:)' in non-final class 'UIImage' must return `Self` to conform to protocol '_BasicTypeTransformable'

**Comment by ac1217** [comment]
反序列是没问题的，UIImage序列化转JSON字符串就不行

**Comment by xuyecan** [comment]
确认在处理有继承关系的类型时，mapper没有正确拿到子类属性的地址。这个问题我尽快处理，争取今晚能给出结论。

**Comment by xuyecan** [comment]
搞半天，发现是设置 `didSet`/`willSet` 后，通过 `&` 符号传址引用时，地址不是属性的真实内存地址。这个问题比较棘手，还要继续研究研究。。

现在如果确实依赖 `didSet`/`willSet` 能力的话，可以先通过用`private`隐藏属性，然后通过 `get/set` 方法访问。

如:
```
class ChatImageMessage: ChatInfoMessage {

    required init() {
        super.init()
    }

    override func mapping(mapper: HelpingMapper) {
        mapper >>> self._image
    }

    var imageUrl: String?

    private var _image: UIImage?
    var image: UIImage? {
        get {
            return _image
        }
        set(new) {
            _image = new
            // did set logic
        }
    }
}
```

我会继续想办法解决这个问题。

**Comment by xuyecan** [comment]
本issue提到的两个问题，都在 [FAQ](https://github.com/alibaba/HandyJSON#faq) 中解答，请参考。
